### ISSUE TITLE
twitter bootstrap

### ISSUE THREAD

**Issue by ujovlado** [marsher/volby-zo-zahranicia#102]
@marsher @scholtz len rychla otazka. Je tam teda pouzity bootstrap ci nie? Z toho co som pozeral vyzera, ze nie, no kopec class sa nan odkazuje. Je to nejaka "work in progress" (niekto ho tam doraba?) alebo tam bol predtym a vyhodili ste ho? Diky.

**Comment by scholtz** [comment]
povodne tam bol bootstrap, ale @musHo urobil design bez bootstrapu, na tagoch od bootstrapu.. ak by si vedel navrhnut lepsie cssko, sem s nim :)

**Comment by ujovlado** [comment]
@scholtz vdaka za odpoved. Ak by som sa do toho pustil, poslem PR. Thx.
