### ISSUE TITLE
Tel.č. ministerstva sa bez trv. pobytu negeneruje

### ISSUE THREAD

**Issue by kaqpa** [marsher/volby-zo-zahranicia#104]
Pokiaľ človek nemá trvalý pobyt na SK, tak sa pri poslednom kroku nezobrazuje tel.č. ministerstva.

**Comment by scholtz** [comment]
vie niekto spravne cislo? :)

**Comment by peterppp** [comment]
nemame cislo. Tety na Minv.sk ale potvrdia e-mailom prijatie spravy a zaradenie do zoznamu

**Comment by scholtz** [comment]
som nastavil ze sa ta sprava nezobrazuje ked nemame cislo..
