### ISSUE TITLE
Testovacia/beta verzia

### ISSUE THREAD

**Issue by roman3x** [marsher/volby-zo-zahranicia#114]
DennikN uz raz o tomto uviedol info, ktoru na ziadost Trubana ze to este nie je hotove stiahol. Vcera o 20h vydali uz clanok https://dennikn.sk/319788/slovakov-zo-zahranicia-urnam-nemobilizuje-stat-aktivisti/, ktory dnes v noci o 2h spropagovali aj na fb https://www.facebook.com/projektn.sk/posts/1053290464760512
Okolo 20h sme tu mali kratkodoby bug s nefunkcnostou na neIOS zariadeni, takze uz je cas, presunut test do zvlast adresara  a na https://volby.digital davat aspon hodinu funkcnu, alebo urcite viacerymi zariadeniami testnutu verziu. 
Neviem, ci to este teraz vidim na zmenu loga na ALFA, a posunutie terminu na 20.12., ako som pisal v https://github.com/marsher/volby-zo-zahranicia/issues/100#issuecomment-164389154, ale vzhladom na problemy #108  by sme mali dalej pracovat tak, ze na test URL bude dostupne testovanie vo vsetkych zariadeniach a na ostrej uz iba prevadzka na podporovanych/funkcnych. JS kodom, ktory zdetekuje z domeny napr "/test/" v URL a OS & verziu prehliadaca. 
Otazka je, ci saskovat s 2kb kniznicou http://pgwjs.com/pgwbrowser/, alebo si to zdetekovat na par riadkov a modlit sa, ci to pobezi vsade? (nie som znalec JS) :)

**Comment by roman3x** [comment]
Detekciu som spravil na 5 riadkov bez kniznice. Vraj to v iHRackach ide. 
- Ak skript bezi v adresari "/test/", tak ma dole pod footrom verziu prehliadaca
- Ak ma nefunkcnu verziu, tak sa pred tlacitkom "Pripravit ziadost" zobrazi cervene upozornenie. Podla mna by malo byt tlacitko vypnute v takomto pripade. V Androide mi to funguje iba v Chrome prehliadaci.

**Comment by scholtz** [comment]
test je tam..

**Comment by scholtz** [comment]
logo na alpha myslim ze nie je treba, a termin by sme mali dodrzat..

myslim ze to nemusime urobit kompatibilne so vsetkymi zariadeniami ktore existuju, ale mali by sme urobit zoznam podporovanych a nepodporovanych zariadeni..

**Comment by roman3x** [comment]
Moja skusenost je, ze je lepsie zdrzat zakaznika(pri cakani na novu ficuru), ako ho nasrat nefunkcnou aplikaciou, co sposobi vacsiu sancu, ze sa uz nevrati. 
Tak ale tu je to pase, lebo DennikN sa rozhodli vyhlasit funkcnost o minimalne 30h skor, ako Vy.

**Comment by scholtz** [comment]
asi chceli byt prvy aj za cenu zverejnenia beta aplikacie..

**Comment by roman3x** [comment]
Urcite. Netusiac, ze je to alfa menom beta :) alfabio
