### ISSUE TITLE
Prvý úvodný popis doplnenie

### ISSUE THREAD

**Issue by JozefSolc** [marsher/volby-zo-zahranicia#119]
V uvodnom popise by malo byt napisane, ze ide o parlamentne volby konane v marci 2016 a ze tioto je nastroj na oficialnu ucast na nich. Zatial to tam nie je.

Mohlo by to byt napr. takto: 

Toto je aplikácia na zjednodušenie Vašej žiadosti na nasledujúce parlamentné voľby poštou zo zahraničia (ktoré sa budú konať 5.3.2015). Žiadosť je potrebné si zaslať najneskôr do  15.1.2016, najlepšie teraz. :) Podrobnejšie všeobecné oficiálne informácie sú tu na stránke MVSR  http://www.minv.sk/?nr16-posta

Zachránime Slovensko
Nevolíme podľa televízie a billboardov

**Comment by roman3x** [comment]
Alebo: (namiesto tej statistiky, ktora by mohla byt v about/inde odkazovana v paticke):

Parlamentné voľby 2016
Tu si môžete zjednodušiť žiadanie o možnosť voliť zo zahraničia, alebo mimo miesta trvaleho bydliska. Stačí ak do 15.1. vyplníte a odošlete nasledujúci _formulár_, na základe ktorého Vám pošlú hlasovacie lístky, ktoré pošlete do X.X.2016 na zadanú adresu obce. Môžete si ho vytlačiť a poslať poštou, alebo najlepšie ho **tu a teraz za 3 minuty** vyplniť a poslať _emailom_, aby ste nezabudli a mali to jednoduchšie.

A pod tlačítkom 

Ak by ste chceli viac informácii, nájdete ich na na stránke MVSR  (url pod textom MVSR http://www.minv.sk/?nr16-posta )

Dátum volieb je pre takéhoto človeka irelevantny. Potrebuje vedieť do kedy to vyplniť a že to môže urobiť tu a teraz. Určite by som úvodnú štatistiku vyhodil.

**Comment by JozefSolc** [comment]
super

**Comment by scholtz** [comment]
zmena je na teste.. môže to byť takto?

https://volby.digital/test/

**Comment by roman3x** [comment]
Zmenil by som z 1.)

> Toto je aplikácia na zjednodušenie vytvorenia žiadosti o možnosti voliť zo zahraničia alebo mimo miesta trvalého bydliska.

na 2.)

> Toto je aplikácia na **zjednodušenie volieb** zo zahraničia alebo mimo miesta trvalého bydliska.

alebo 3.)

> Aplikácia na **zjednodušenie volieb** zo zahraničia alebo mimo miesta trvalého bydliska.

---

A v tretej vete z:

> alebo najlepšie ju

na 

> alebo najjednoduchšie ju

---

Prípadne ju celú zmeniť z:

> Žiadosť môžete poslať poštou, alebo najlepšie ju tu a teraz za 3 minúty vyplniť a poslať emailom, aby ste na to nezabudli a mali to jednoduchšie. 

Na:

> Žiadosť najjednoduchšie pošlete tu a teraz za 3 minuty mailom, alebo ju môžete poslať poštou. Ale prečo robiť niečo papierovo, keď to ide aj elektronicky?

**Comment by roman3x** [comment]
Chyba tam zasadna vec - do kedy sa to ma vyplnit. ;) To by som dal napríklad na pravú stranu k logu

> Požiadajte do 15.1.

**Comment by roman3x** [comment]
Pozeram, ze to tam je, ale iba pre tych s trvalym pobytom na slovensku. Pre netrvalopobytovych info chyba. Nedame tieto info na uvodnu stranku? Citam po sebe ten bazmek https://github.com/marsher/volby-zo-zahranicia/issues/119#issuecomment-164905595 ... :D 
Zda sa mi to preplacane aj ostra aj test verzia. A este by som tam aj datumy chcel...
