### ISSUE TITLE
rozsirenie info

### ISSUE THREAD

**Issue by mtruban** [marsher/volby-zo-zahranicia#12]
nebolo by odveci, vyuzit aj kopec obsahu a uzitocnych info z tejto stranky: http://www.cybest.sk/
(pripadne na nu nalinkovat)

(je to z platformy)

source:  https://github.com/cybest/volby-na-dialku

**Comment by scholtz** [comment]
pripadne http://volby.scholtz.sk :)

**Comment by mtruban** [comment]
ale niekde by sa to zislo fakt nalinkovat... ze pre viac info pre ludi

**Comment by scholtz** [comment]
dal som to do readme na gite
