### ISSUE TITLE
Datum dorucenia ziadosti

### ISSUE THREAD

**Issue by ghost** [marsher/volby-zo-zahranicia#120]
Krok 2 - (Žiadosť treba poslať najneskôr do 15.1.2016) resp.15.2. v pripade volicskeho preukazu

K danym datumom musi byt ziadost obdrzana obcou, nie poslana. Navrhujem upravit text  "Žiadosť treba poslať najneskôr" na "Žiadosť musí byť doručená najneskôr". Pre pripad posielania ziadosti zo zahranicia postou namiesto emailom navrhujem vyzvat userov poslat ziadost do 31.12. 2015.

**Comment by scholtz** [comment]
fix je na teste:  https://volby.digital/test/

@Rabaka Dik za tip
