### ISSUE TITLE
Chcem tlačiť - ako na to?

### ISSUE THREAD

**Issue by milossramek** [marsher/volby-zo-zahranicia#121]
Zdravím,

veľmi dobrý nápad :)
Aplikácia je trochu príliš orientovaná na telefón/tablet s funkčnou možnosťou podpisovania. Ja takú možnosť nemám, a tak v kroku 5. som zvolil "Stiahnuť". Teraz môžem vytlačiť, podpísať a odoslať.

Ak by som podpísal cez telefón, tak by mi aplikácia pomáhala aj ďalej. Pritom postup je prakticky rovnaký ako v prípade tlačenia a skenovania  (len sa vynechá krok 6). Navrhujem: po stlačení "Stiahnuť" zobrazte krok 6 s inštrukciami:
Prvá možnosť: Žiadosť vytlačte, podpíšte a poštou aj s prílohami pošlite na adresu, ktorá je v nej uvedená. 
Druhá možnosť: Žiadosť vytlačte, po podpísaní zoskenujte a **odošlite e-mailom**. 

**odošlite e-mailom** bude odkazom na krok 8. 

A netreba ísť na poštu.
Vďaka vopred
Miloš

**Comment by scholtz** [comment]
zdravím..

skôr mi vyznieva otázka, že prečo Vám nefunguje podpisovanie..

podpísať sa štandardne dá myškou alebo rukou na obrazovke..

ak by sme do kroku 5 dali inštrukcie že si to majú vytlačiť tak pre väčšinu ľudí ktorým aplikácia funguje aj s podpisovaním to bude zmätočné.. nie?

aký operačný systém a prehliadač používate?

**Comment by milossramek** [comment]
On 2015-12-15 19:44, Ludovit Scholtz wrote:

> zdravím..
> zdravim.
> 
> skôr mi vyznieva otázka, že prečo Vám nefunguje podpisovanie..
> 
> podpísať sa štandardne dá myškou alebo rukou na obrazovke..
> No to funguje, len ja mam  touchpad bez tlacitiek, ktory je na hranici
> pouzitelnosti aj pri beznom pouziti. To co dokazem vytvorit sa na moj
> podpis nijako nepodoba.
> Mozno 3 kriziky by som zvladol lepsie
> 
> ak by sme do kroku 5 dali inštrukcie že si to majú vytlačiť tak pre väčšinu ľudí ktorým aplikácia funguje aj s podpisovaním to bude zmätočné.. nie?
> V piatom kroku už je tlacitko "Stiahnuť". Ak na to kliknem, tak sa mi
> zobrazí pdf-ko, a to je vsetko. Chvilu mi trvalo, kym som si uvedomil,
> ze viac nebude a ze si to mam vytlacit, vlozit do obalky a poslat.

Ak by sa zobrazila dalsia obrazovka s instrukciami a potom by to preslo
na obr. 8, tak by to bolo jasne a pomohlo by a nemusel by som posielat
list. Mozno pripadne prejst proiamo z 5 na 8

Ak niekto chce podpisovat, tak v 5. kroku stlaci Podpisat a ide dalej
bez problemov.

Postup obrazoviek:

Ak idem podpisovať (som v zahranici, aj ked nie dalekom)
1 (klikam V zahranici), 4 (klikam Vytvor nahlad..), 5 (klikam Podpisat),
6 (klikam Pouzit), 7 (klikam stiahnut, potom klikam Po ulození...), 8
(klikam vytvorte email)

Druhy postup by mohol byt takyto:
1 (klikam V zahranici), 4 (klikam Vytvor nahlad..), 5 (klikam Podpisat),
6 (klikam Stiahnut), 8 (klikam vytvorte email)

Vlastne teda spraviť len to, že pri kliknuti n a existujuce tlacidlo
Stiahnut na obr. 5 sa okrem otvorenia ziadosti prejde na obr 8. Tak by
to mohlo stacit.

> aký operačný systém a prehliadač používate?
> Ubuntu 15.04 a FF 42.0

vsetko dobre,
Milos

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/marsher/volby-zo-zahranicia/issues/121#issuecomment-164851814

## 

Milos Sramek, msramek22@gmail.com

**Comment by roman3x** [comment]
@scholtz Nebolo by dobre, mat tam vsade otazku "Nieco Vam nefunguje? / Neviete, ako dalej?" a za nou odklik na informacnu stranku. Kde budu bud vysvetlivky k danemu kroku.

@milossramek Priamy prechod z 5 na 8 by mohol sposobit zbytocne viac ludi podpisujucich a posielajucich ziadost pisomne. Co ste ani Vy nechcel. :D Takto podpisete "elektronicky" a mate za dalsie 2 minuty pokoj so ziadostou. :)

**Comment by milossramek** [comment]
On 2015-12-15 22:27, roman3x wrote:

> @scholtz Nebolo by dobre, mat tam vsade otazku "Nieco Vam nefunguje? / Neviete, ako dalej?" a za nou odklik na informacnu stranku. Kde budu bud vysvetlivky k danemu kroku.
> 
> @milossramek Priamy prechod z 5 na 8 by mohol sposobit zbytocne viac ludi podpisujucich a posielajucich ziadost pisomne. Co ste ani Vy nechcel. :D Takto podpisete "elektronicky" a mate za dalsie 2 minuty pokoj so ziadostou. :)

Možno mate pravdu, nic zasadne netreba menit. V tom prípade ale treba
texty na stránke upraviť, aby to bolo jasné ako postupovať aj takým
použivateľom, ako som ja. Navrh zmeny textu pripajam, keby github
prilohy nebral, je tu:  https://copy.com/vT3911Yq7tDqLVp6

Navrhy su zltym

Milos

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/marsher/volby-zo-zahranicia/issues/121#issuecomment-164902233

## 

Milos Sramek, msramek22@gmail.com

**Comment by scholtz** [comment]
Sme pridali tlacitko pomoc na vrch stranky..

zatial je to na teste..  https://volby.digital/test/

moze to ostat takto?

**Comment by roman3x** [comment]
- Pár px podrásť by mu neuškodilo a aj dalej od čísovania krokov. "Späť na úvod ide posunúť pre ten účel dole. 
- 4/8 Nepridas sem cast infromacii o moznosti Poste Restante pre tych kamionistov, ktorych je vraj cez vikend odhadom 2000 vonku + dalsi stahujuci sa atd. ludia? Alebo odkaz na README.md... alebo to presunut na samostatnu stranku do wiki. 
- 5/8 "Tu je zobrazený náhľad dokumentu. Ak je všetko vporiadku..." Ja tam ani na PC, ani na Androide nevidim nic, aj ked ked to stiahnem to tam mam. :D Takze po tejto info by som mozno nesiel dalej... Pridaj aj niečo v zmysle "Ak náhľad nevidíte, možno to Váš prehliadač nepodporuje a pre kontrolu si môžete dokument stiahnuť"
- 6/8 Ludia su si neisty, ze sa nevedia dobre podpisat na mobile, alebo myskou na pc. Tak ich trosku vhodnou vetou usmernit k odvahe to urobit. Ze tu nejde o dokonalost...
- Na stránke 7/8 z vonku by som určite neobŤažoval zvýrazňovaním slov ZEP, ale radšej "Podpisovanie ZEPom nie je vyžadované pre voľby". Spisovne je "Vášho". Dúfam. :) 
- 8/8 "prípadne fotky pasu" to znamena co? je to niekedy povinne a niekedy nie, alebo je to doporucene?
- Niektori mobilni useri nebudu vediet _vložiť_ text do emailu. Aj to by som do vysvetliviek dal.

**Comment by roman3x** [comment]
Stale si myslim, ze je tam bug v kroku 4/8, kde moznost volby formatu adresy USA vs noUSA vidim iba pri ziadani o hlasovaci preukaz na volbu z domova a nie pri hlasovani postou zo zahranicia. 
Viď #71

**Comment by scholtz** [comment]
bug je opraveny na teste..

ja sa snazim nerobit design a texty .. (velmi mi to nejde) :) 
to tlacitko som dal na standardnu bootstrapovu velkost btn btn-default btn-xs

4/8 nie som si isty, ci uradnicky su tiez s Poste Restante vpohode...

"Niektori mobilni useri nebudu vediet vložiť text do emailu" tomu nechapem..

ostatne je zhruba implementovane na teste..

**Comment by roman3x** [comment]
Jasne, mne design nejde vobec. :)
Neviem, ako by dopadol predvyplneny formular Barcelonou, ci by to viacej ludi neprehliadlo a nenechalo si tam poslat tie listky...
Myslel som to tak, ze by to bolo v combe "Formát adresy" pridat aj moznosti pre Poste Restante a onChange to vyplni Ulicu a cislo a pre ameriku v opacnom poradi... A najlepsie aj ze by to zmenilo v pdf. Spravim ja, ak sa Ti uz nechce. 

Co sa organizacnej otazky tyka, volal som aj na postu, aj na ministerstvo vnutra. Clovek, co to riesi povedal, ze prave kvoli moznosti ze by listky sa mohli stratit sa to bude posielat s dorucenkou. A posielanie s dorucenkou Poste Restante mi potvrdili na infolinke posty. S vyhradou niektorych krajin. Tak ten pan mi povedal, ze nech sa v pripade dakej exotickej krajiny pokusi dohodnut s vlastnym obecnym uradom, nech to poslu obycajnym Poste Restante. 

Amaterski pouzivatelia PC a mobilov casto nevedia ako text, ktory uz dostanu tlacitkom do schranky vlozia do mailu. Musis sa bavit nielen s intelektualmi, ale aj s beznymi volicmi. ;)

**Comment by scholtz** [comment]
kludne to tam implementuj.. dik

**Comment by scholtz** [comment]
dik za implementaciu.. to prehlasenie som vsak nechal, lebo v zakone je napisane ze to musi byt dorucene ako priloha.. aby nahodou nezacali uradnici nahanat ludi ze im nedali prehlasenie..

mozme tuto issue uzavriet?

**Comment by roman3x** [comment]
Ososbne som si vsimol prehlasenie az ked som to tu niekde cital - ze je na druhej strane. :D Podla #31 by mala byt akceptovana aj jednostranova verzia. Ale ok. Este ze som Ti nemazal aj funkciu na inline adresu. :)

**Comment by kaqpa** [comment]
Poste Restante sa ale neda pouzit na uradne zasielky, nie? Alebo je s tym ministerstvo v pohode?

**Comment by roman3x** [comment]
Volal aj pisal som na infolinku posty a volal na ministerstvo vnutra a ked to bude dorucene nebude problem. A zasielka "na postu" moze byt doporucene.  Vo vlastnom zaujme. A posta to v zahranicnom styku umoznuje. Niektore staty na svete nie, ale tam nasincov vela nebude. 
Toto je z mailu:

> v pripade, ze si chcete vo Vasej adresnej krajine nechat zaslat zasielky "na postu" je nutne si overit ci Vasa krajina v ramci postovych podmienok taketo zasielky prijima. Na stranke Slovenskej posty v casti: 
> http://cennik.posta.sk/ 
> si viete overit cenu doporucenych zasielok do jednotlivych krajin sveta. 
> Dakujeme za pochopenie.

**Comment by scholtz** [comment]
nedavno bol urobeny fix, a ak sa clovek nepodpise, tak sa mu nezobrazi hlaska aby sa podpisal, ale potvrdzovacia hlaska ze sa chysta pokracovat bez podpisania..

je to na teste: http://volby.digital/test/

Mozme tuto issue uzavriet?
