### ISSUE TITLE
mala chyba v texte

### ISSUE THREAD

**Issue by chovajsa** [marsher/volby-zo-zahranicia#126]
Nechyba tam "žiadam" alebo tak ? Akoby v tej prvej vete chybal prisudok. 

"... výkonu volebného práva a o zmene a doplnení niektorých zákonov **žiadam** o vydanie hlasovacieho preukazu pre voľby... "

![screen shot 2015-12-16 at 15 14 17](https://cloud.githubusercontent.com/assets/2128708/11843064/b6355a4a-a407-11e5-921d-16008c341014.png)

**Comment by scholtz** [comment]
Áno. Ďakuejme za tip na úpravu. Úprava bola implementovaná.
