### ISSUE TITLE
Pridanie licencie

### ISSUE THREAD

**Issue by jbub** [marsher/volby-zo-zahranicia#132]
Ahojte, super praca, mozno by nebol zly napad pridat licenciu pod ktorou je tento kod dostupny :)
- https://help.github.com/articles/open-source-licensing/
- http://choosealicense.com/
- http://stackoverflow.com/questions/4007674/whats-the-default-license-of-code-published-at-github

**Comment by oskopek** [comment]
+1

**Comment by scholtz** [comment]
MIT
