### ISSUE TITLE
Daju sa odoslat aj prazdne formulare

### ISSUE THREAD

**Issue by filiplikavcan** [marsher/volby-zo-zahranicia#133]
Pri odosielani formulara nie je kontrola, ci boli zadane povinne udaje. Myslim, ze to znizi chybovost (a zvysi ucast vo volbach), ked sa spravi kontrola povinnych udajov pri odosielani formulara.

**Comment by scholtz** [comment]
otazka skor je, ci budeme obmedzovat ludi ked nechcu vyplnat nejake udaje, ze si to doplnia npr rucne po vytlaceni.. 

alebo ci vsetky formy nasej validacie su urcite spravne.. npr nasa db psc je najaktualnejsia, ale ak by chcel niekto zadat starsiu PSC (mozno nezaregistroval zmenu) tak by mu to mozno neslo a bol by nahnevany..

viem ze v ba sa menili psc npr.. nove pouzivame 82102 a stare si nepametam

dalej co ak nechce vyplnit ulicu, lebo je to v dedine kde nie su pomenovane ulice?

validator musi fungovat na 100% pred tym ako im zakazeme pokracovat..

**Comment by filiplikavcan** [comment]
Chcelo by to minimalne upozornenie, ze clovek nevyplnil policka, ktore “pravdepodobne” mal vyplnit a moznost sa rozhodnut, ze OK, idem dalej alebo, ze to chcem doplnit.

## 

Filip Likavčan
bratia.sk s.r.o.

kancelária: Miletičova 21, 821 09 Bratislava
email: filip@bratia.sk
mobil: +421 910 926 942
web: http://bratia.sk/

fakturačná adresa: Krajná 7, 821 04 Bratislava

Ako ste boli spokojný s mojou odpoveďou? Ohodnoťte ma na:
https://www.nicereply.com/bratia-sk/filip

**Comment by scholtz** [comment]
hej, to je super napad.. som to implementoval, je to na teste

**Comment by Rabaka** [comment]
Looks good. Vdaka.

**Comment by roman3x** [comment]
Kontrola PSC sa uspokojila s hocicim. Implementovat som pri kontrole PSC kontrolu 5 cisel a zavolanie funkcie findZIP() je samostatne pri 5 cislach s neovplyvnenim validacie. Neviem, ci je to dobre...
