### ISSUE TITLE
Chybne instrukcie pri odlasenom pobyte na SR

### ISSUE THREAD

**Issue by ghost** [marsher/volby-zo-zahranicia#138]
SR konzul v DC odporuca upravit spodne instrukcie v kroku 8 v podaní žiadosti o voľbu poštou na MV SR, občana SR, ktorý nemá trvalý pobyt v SR.

Instrukcie na apke su nasledovne: "Po odoslaní emailu s prílohou očakávajte potvrdenie z obecného úradu...."

Issue - obcanov odhlasenych z trvaleho pobytu vybavuje MV, nie obec.

**Comment by scholtz** [comment]
Dobrý deň, ďakujeme za tip úpravy aplikácie. Zmeny boli implementované a sú dostupné v teste: https://volby.digital/test/

**Comment by ghost** [comment]
Looks good. Vdaka.
