### ISSUE TITLE
Chyba ciselniku PSC 04022 je Košice - Sídlisko Dargovských hrdinov 

### ISSUE THREAD

**Issue by jjuris** [marsher/volby-zo-zahranicia#145]
Poprosim opravit 
Dakujem

**Comment by jjuris** [comment]
Upravil som riadok 1569 snad som nic nepokazil :) 
Košice - Dargovských hrdinov  Dargovských hrdinov    Košice III 040 22      Poz. zoz.ulíc Košice  804 KI

**Comment by jjuris** [comment]
Ten pull som stiahol, kazdopadne by moja adresa Kpt. Jaroša 1 a PSC 04022  Košice mala vegenerovat Košice - Sídlisko Dargovských hrdinov 
dakujem

**Comment by scholtz** [comment]
Ahoj, PSČ 04022 je pre viac oblastí, nie len pre tvoje sídlisko.. Sídlisko KVP má podľa všetkého viac obyvateľov..

**Comment by jjuris** [comment]
Ahoj no tak tomu teda nerozumiem, Sidlisko Darg. hrdinov je najvacsie a najludnatejsie v Kosiciach, okrem ineho je na opacnom konci kosic ako KVP, som presvedceny ze sa jedna o chybu

Prosim o korekciu

**Comment by jjuris** [comment]
THIS IS IT

> > > > > > > > Miestny úrad mestská časť Košice - Dargovských hrdinov  
> > > > > > > > Státní správa

Adresa: Dvorkinova, 040 22 Košice-Dargovských hrdinov, Slovensko
Telefon:+421 55/671 78 33

**Comment by scholtz** [comment]
Dakujeme za informaciu.. 

Specialne sme dorobili kosice.. Problem bol v tom, ze psc podla oficialneho zdroja (z posta.sk) nezobrazovalo mestske casti.. Sme to naparovali podla http://www.kosice.sk/ulice.php a uz by to malo byt ok..

Pre kontrolu:

Stare udaje:

'04001':['kosice-stare-mesto','Košice','Košický'],
'04011':['kosice-peres','Košice','Košický'],
'04012':['kosice','Košice','Košický'],
'04013':['kosice-tahanovce','Košice','Košický'],
'04014':['kosice-kosicka-nova-ves','Košice','Košický'],
'04017':['kosice-barca','Košice','Košický'],
'04018':['nizna-hutka','Košice okolie','Košický'],
'04022':['kosice','Košice','Košický'],
'04023':['kosice','Košice','Košický'],

Nove udaje:

'04001':['kosice-zapad','Košice 2','Košický'],
'04011':['kosice-zapad','Košice 2','Košický'],
'04012':['kosice-nad-jazerom','Košice 4','Košický'],
'04013':['kosice-sidlisko-tahanovce','Košice 1','Košický'],
'04014':['kosice-dargovskych-hrdinov','Košice 3','Košický'],
'04017':['kosice-juh','Košice','Košický'],
'04018':['kosice-krasna','Košice 4','Košický'],
'04022':['kosice-dargovskych-hrdinov','Košice 3','Košický'],
'04023':['kosice-zapad','Košice 2','Košický'],

Zmena bola dana zatial na test: https://volby.digital/test/

**Comment by scholtz** [comment]
Ale ako tak pozeram, tak z nejakeho dovodu z e-obce sme dostali 2x sidlisko tahanovce.. 

http://www.tahanovce.net/ vs. http://www.tahanovce.eu/

adresa uradu:
Americká trieda    15  040 13  Košice vs. Ťahanovská    28  040 13  Košice

co je z tohto spravne?

**Comment by jjuris** [comment]
Ahoj 
otestoval som, funguje,  :) :+1:

**Comment by jjuris** [comment]
Ohladom Tahanoviec myslim si ze oboje pretoze:  
Ťahanovská 28 040 13 Košice http://www.tahanovce.eu/ je "historicka" dedina, ktora bola pohltena Kosicami
Americká trieda 15 040 13 Košice  http://www.tahanovce.net/ je sidlisko, ktore vyrastlo prave nad tou dedinou

**Comment by scholtz** [comment]
a budu vediet kosicania urcit spravny urad pre nich? aby to z tej historickej dediny neposielali na to sidlisko.. ked maju aj rovnake psc...

?

**Comment by jjuris** [comment]
Myslim si, ze ak na "tahanovcana" vyskoci  alert "ak si z valalu tak si zvol urad 1, ak si zo sidliska tak si zvol iny urad 2" tak vyberie ten korektny :)

**Comment by jjuris** [comment]
Na druhu stranu je velmi pravdepodobne ze clovek zijuci v zahranici si nevsimne alebo nebude poznat adresu svojho skutocneho uradu... tazko povedat a ak je aj to PDFko editovatelne, tiez si dovoim tvrdit ze bezny uzivatel ktory ma na PC nainstalovany Adobe Reader a chybu si aj vsimne, mozno nebude vediet ako editovat vygenerovany subor, takze to bude chciet asi troska skomplikovat program no :)

**Comment by jjuris** [comment]
Ahoj tak som sa spytal kamosky z tahanoviec - sidliska, jej ziadost bola odoslana prave do dediny ale pani uradnicka ju preposlal na sidlisko, takze asi nie je potreba riesit, pani z dediny je dostatocne sikovna :)

**Comment by scholtz** [comment]
ok, super

mozem tuto issue uzavriet?

**Comment by jjuris** [comment]
Ja to zavriem, mozno este jedna pripmienka, mailova adresa stale smeruje na sidisko kvp :) 
uvidim ako na to zareaguju uradnici popripade sa ozvem 
dakujem a pekny vecer

**Comment by scholtz** [comment]
Mne po zadani 04022 v testovacom systeme da adresu:

Miestny  úrad 
Dvorkinova 7
040 12 Košice
karabasova@kosice-dh.sk

to nie je spravne?

**Comment by jjuris** [comment]
Jop to je ale v poslednej stanke kde je to tlaciko na copy do schranky mi skopirovalo sekret@mckvp.sk

**Comment by scholtz** [comment]
toto neviem replikovat.. urcite ti to nejde na testovacej stranke? skus stlacit ctrl f5 pre obnovu cachovanych suborov..

**Comment by jjuris** [comment]
ospravedlnujem sa, ja som si PDFko generoval na iPade kvoli podpisu a na PC som si vygeneroval emailovy text. PDF som generoval na Teste a text na Produkcii .Testovaci system funguje spravne zavaram
