### ISSUE TITLE
Tahanovce sidlisko vs Tahanovce obec

### ISSUE THREAD

**Issue by gabcheese** [marsher/volby-zo-zahranicia#147]
po zadani psc 04013 mi vyhodi adresu a email na Kosice-Tahanovce obec a nie Tahanovce sidlisko, tym padom je to nespravne adresovany a posielany request 

(sorry, nie som ziadny it clovek, ale vsimla som si tento problem a neviem ako vas inac kontaktovat.. a nechcem, aby niekto prisiel o sancu volit.. a vacsina potencialnych volicov je sto pro z 23 tisicoveho sidliska a nie dediny)

**Comment by scholtz** [comment]
Ano, toto je uz opravene na teste: https://volby.digital/test/

**Comment by scholtz** [comment]
Bolo to rozoberane tu: https://github.com/marsher/volby-zo-zahranicia/issues/145

**Comment by scholtz** [comment]
uz je to aj na produkcii
