### ISSUE TITLE
pridat google analytics

### ISSUE THREAD

**Issue by mtruban** [marsher/volby-zo-zahranicia#15]
- aby sme mali stats, ked sa pojde s tym von

**Comment by musho** [comment]
Pridat GA events na kroky. Aby sme videli cely funnel + kde sa ludia zasekavaju najviac.
(GA nema behavior udaje, kedze je to one-pager).

**Comment by s7anley** [comment]
@musHo je to mergnuté, ale zatiaľ asi nie nasadené. Môžeš mrknúť do PR či vyhovuje konfigurácia eventov?
