### ISSUE TITLE
Formulacia chybovej validacnej hlasky

### ISSUE THREAD

**Issue by OndroNR** [marsher/volby-zo-zahranicia#156]
Ide napr. o ["Ulica adresy kde chcete odoslať žiadosť nemôže byť nevyplnená."](https://github.com/marsher/volby-zo-zahranicia/blob/master/js/validation.js#L173). Neviem ci ide o adresu odkial posielam ziadost alebo o adresu kam pride odpoved. Pride mi to, ze to miesa dve veci (odoslanie, prijem) dokopy. A ten dvojity zapor tiez nie je najstastnejsi.

**Comment by scholtz** [comment]
ale adresa odkial sa vyplna ziadost tam nie je..

ale dakujeme za tip, a hlasku sme zmenili na 
"Vaša ulica kam si chcete odoslať hlasovacie lístky alebo hlasovací preukaz musí byť vyplnená."

zmenené texty sú v teste: https://volby.digital/test/

Môže to ostať takto?

**Comment by OndroNR** [comment]
Myslim, ze moze. Vdaka.
