### ISSUE TITLE
PSC 84104 je namapovane na Petrzalku, ma to byt Karlova Ves 

### ISSUE THREAD

**Issue by pavolzibrita** [marsher/volby-zo-zahranicia#158]
PSC 84104 je namapovane na Petrzalku, ma to byt Karlova Ves 

Pri zadani psc 84104 sa zvoli Petrzalka, Bratislava 5 namiesto Bratislava 4.

**Comment by scholtz** [comment]
Dobrý deň, ste si istý, že v Petržalke sa nepoužíva PSČ 84104 alebo počet ľudí v Petržalke s týmto PSČ je menší ako v Karlovej Vsi?

**Comment by scholtz** [comment]
Mohli by ste prosím skontrolovať, či PSČ teraz sedí?

Prosím pokračovať konverzácie v issue  #159
