### ISSUE TITLE
Formular neakceptuje cisla POBOX

### ISSUE THREAD

**Issue by rlaffers** [marsher/volby-zo-zahranicia#160]
V subore POBoxy.XLS v http://www.posta.sk/sluzby/postove-smerovacie-cisla su rozsahy platnych PSC pre POBOXy. Bolo by fajn, keby formular akceptoval aj taketo cisla. 
Priklad: 83302
Momentalne pise ze ho nema v zozname.

**Comment by scholtz** [comment]
psč pre poboxy boli implementované, ale pre ba sa mi nechcelo riešiť jednotlivé oblasti..

kto má ináč trvalý pobyt v POBoxe? :)

**Comment by rlaffers** [comment]
To je pre ľudí, ktorí sú na cestách. Hlasovací preukaz si môžu nechať poslať v meste kde sa budú zdržovať do poboxu.

**Comment by scholtz** [comment]
ale to vyplna adresu pre trvaly pobyt a nie pre miesto odoslania.. a pre miesto odoslania sa to velmi neda, lebo to moze byt kdekolvek na svete.. :)

**Comment by rlaffers** [comment]
Aha, ok - v tom pripade toto mozeme zavriet.
