### ISSUE TITLE
PSC 04023 ma byt Sidlisko KVP

### ISSUE THREAD

**Issue by turboluk** [marsher/volby-zo-zahranicia#162]
Netusim, ci som prvy zaujemca o ziadost z KVP, ale domnievam sa, ze moji predchodcovia si nevsilmli, ze 04023 nepatri pod Kosice - Zapad.  http://www.kosice.sk/ulice.php?go=&ulica=&mc=kvp&psc=

pribuzny problem: #145

Kontakt: http://www.mckvp.sk/kontakty/

**Comment by scholtz** [comment]
dakujeme.. bola najdena chyba, ze na tej stranke je KVP vedene ako KVP, a v zozname obci je vedene ako sidlisko KVP.. teraz by to uz malo fungovat.. zaroven bol implementovany novy algoritmus pre vypocet poctu obyvatelov v oblasti.. viac info tu: #159

novy zoznam pridelenia psc k uradom v ke je tu:

'04001':['kosice-stare-mesto','Košice','Košický'],
'04011':['kosice-zapad','Košice 2','Košický'],
'04012':['kosice-nad-jazerom','Košice 4','Košický'],
'04013':['kosice-sidlisko-tahanovce','Košice 1','Košický'],
'04014':['kosice-kosicka-nova-ves','Košice','Košický'],
'04015':['kosice-saca','Košice','Košický'],
'04016':['kosice-myslava','Košice','Košický'],
'04017':['kosice-barca','Košice','Košický'],
'04018':['kosice-krasna','Košice 4','Košický'],
'04022':['kosice-dargovskych-hrdinov','Košice 3','Košický'],
'04023':['kosice-sidlisko-kvp','Košice','Košický'],

je to spravne?

**Comment by scholtz** [comment]
by ma zaujimalo ze aky je rozdiel medzi okresom Kosice, a okresom Kosice 1 npr.. nieco sa mi na tom nezda..

**Comment by turboluk** [comment]
Okres Kosice neexistuje, existuju Kosice 1 az 4. Sidlisko KVP patri pod Kosice 2.

Posledny riadok by som upravil nasledovne:
'04023':['kosice-sidlisko-kvp','Košice 2','Košický'],

**Comment by scholtz** [comment]
takto je to ok? 

'04001':['kosice-stare-mesto','Košice 1','Košický'],
'04011':['kosice-zapad','Košice 2','Košický'],
'04012':['kosice-nad-jazerom','Košice 4','Košický'],
'04013':['kosice-sidlisko-tahanovce','Košice 1','Košický'],
'04014':['kosice-kosicka-nova-ves','Košice 1','Košický'],
'04015':['kosice-saca','Košice 1','Košický'],
'04016':['kosice-myslava','Košice 1','Košický'],
'04017':['kosice-barca','Košice 1','Košický'],
'04018':['kosice-krasna','Košice 4','Košický'],
'04022':['kosice-dargovskych-hrdinov','Košice 3','Košický'],
'04023':['kosice-sidlisko-kvp','Košice 2','Košický'],

**Comment by turboluk** [comment]
Ano.
