### ISSUE TITLE
Nefunguje vytvorenie náhľadu žiadosti

### ISSUE THREAD

**Issue by matejpavlovic** [marsher/volby-zo-zahranicia#165]
Dobrý deň,

Po vyplnení všetkých údajov a kliknutí na "Vytvor náhľad žiadosti" sa nič nestane. Browser console pri každom kliku zobrazí chubu:

ReferenceError: signaturePad is not defined
createDocument()
 request.js:19
RequestGeneratorApp.prototype.submitForm()
 request-generator-app.js:233
RequestGeneratorApp.prototype.init/<()
 request-generator-app.js:30
m.event.dispatch()
 jquery-latest.min.js:3
m.event.add/r.handle()
 jquery-latest.min.js:3
 request.js:19:7

Skúšal som to v týchto prehliadačoch:
Ubuntu 14.04: Firefox 43.0 a Chrome (Chromium Version 47.0.2526.73 Ubuntu 14.04 (64-bit))
Windows 8.1: posledný Firefox a Chrome

**Comment by joseph11** [comment]
Ani mne nejde generovat nahlad ziadosti - hlasi rovnaku chybu ako je uvedene vyssie.

Testovane tiez na Ubuntu 14.04 (Chromium a Firefox - rovnake verzie ako vyssie)

**Comment by vojtuus** [comment]
mam ten isty problem
Windows 7 a Android 5.1: posledne verzie Firefox aj Chrome

**Comment by japutko** [comment]
To isté u mňa: Win7 - Chrome / IE (posledne verzie)

**Comment by scholtz** [comment]
stále hlási túto chybu?

nedarí sa mi to replikovať..

k tomuto riadku sa to dostane? 

``` javascript
  App.signaturePad = new SignaturePad(canvas);
```

Dá sa to otestovať tak, že v developer tools sa vloží brake na ten riadok.. (App.js riadok 73)

**Comment by matejpavlovic** [comment]
Už to funguje. SignaturePad sa vytvorí hneď pri načítaní úvodnej stránky.

**Comment by joseph11** [comment]
Aj mne to uz funguje. (Ubuntu 14.04, Chromium)

**Comment by matejpavlovic** [comment]
Vďaka za rýchlu opravu, zatváram issue.
