### ISSUE TITLE
Zavadzajuce udaje, ktore odradzuju pouzit aplikaciu.

### ISSUE THREAD

**Issue by kivoo** [marsher/volby-zo-zahranicia#166]
Na zaciatku ziadosti je uvedene, ze ``Žiadne údaje nie sú odosielané cez internet ´´.
To je mätúce, keďze samotná apikácia vybáda k tomu, aby ziadatel zadal na webovej stranke osobne udaje...
Bolo by dobre hned na zaciatku jasne vymedzit, ze aplikacia iba vytvara ziadost ale neumoznuje hned aj odoslanie ziadosti (co je na druhej strane skoda). Mna to odradilo a radsej som o hlasovaci listok poziadal osobne. Inych to iba odradi a nepoziadaju vobec.

**Comment by m1k1o** [comment]
Webová aplikácia neodosiela cez internet nič. Všetky údaje sú spracované na strane užívateľa cez JavaScript.

**Comment by kivoo** [comment]
uz to bolo upravene, je to zrozumitelnejsie
dik
