### ISSUE TITLE
update emailovej adresy v database

### ISSUE THREAD

**Issue by geroj** [marsher/volby-zo-zahranicia#167]
Dostal som odpoved od obecneho uradu vo Vidinej po registracii, ze pouzivaju nove adresy:

Dobrý deň, Váš email sme zaevideovali, zároveň Vám dávame do pozornosti, že Obec Vidiná už používa nové mailové adresy, obec@vidina.sk bola nahradená podatelna@vidina.sk
S pozdravom

**Comment by scholtz** [comment]
dakujeme
