### ISSUE TITLE
Do buducna moznost nahrat obrazok s digitalnym podpisom

### ISSUE THREAD

**Issue by petergaal** [marsher/volby-zo-zahranicia#169]
Uz sice tento rok to nebude zaujimave, kedze som to odoslal, ale volby budu aj o 4 roky (a predpokladame, ze tento projekt mozno aj dovtedy prezije). Podpisat sa pomocou mysi je celkom problem (cez touchpad este horsie) a sice mam dotykovy screen, ale stylus som nechal v zahranici, takze vysledok je bieda. Bolo by dobre mat moznost aj nahrat uz vytvoreny podpis z obrazku a pouzit to (standardne si to davam aj na faktury uz takto, co som raz naskenoval). Neviem, ako sice vyriesit problem s roznymi velkostami obrazku, ale urcite sa to da vyriesit tiez.

**Comment by scholtz** [comment]
nahravanie suborov do html stranky bez pouzitia servera asi nebude velmi podporovane vo vsetkych prehliadacoch.. je tu niekto kto sa v tomto vyzna lepsie? :)
