### ISSUE TITLE
Ak sa tam zadava Rodne cislo, tak aj info o ochrane osobnych udajov

### ISSUE THREAD

**Issue by roman3x** [marsher/volby-zo-zahranicia#19]
Potvrdenie suhlasu a mozno aj projekt k tomu vytvorit, nech ma uradny simel radost.

**Comment by marsher** [comment]
Potrebujeme ho ak je to cele client-side?

**Comment by petergaal** [comment]
Potom by mala byt o tom informacia, ze je to cele len v prehliadaci a osobne udaje sa neodosielaju na server.

**Comment by mtruban** [comment]
ta je hned na hlavnej stranke. ale zvyraznime urcite.

**Comment by filiplikavcan** [comment]
Mozno by tam mohla byt informacia, ze ak si chce byt niekto naozaj isty, ze to neodosiela nic na server, tak nech sa odpoji z netu pocas generovania PDFka, potom zatvori stranku a az potom zapne net.

**Comment by mtruban** [comment]
mozno tento text: Žiadne osobné dáta nie sú prenášané internetom (dat cervenym)

pripadne ho zduplikovat na viacerych castiach webu.

**Comment by peterppp** [comment]
nieco ako:
tento nastroj nie je nevyhnutny - kludne si mozte ziadost vytlacit, vyplnit rucne a oscanovat.

**Comment by scholtz** [comment]
ja by som dal niekde na stranku este, ze pdf mozete podpisat zarucenym elektronickym podpisom a tym ubezpecit uradnikov ze to posielate vy :)

**Comment by roman3x** [comment]
Ci nebude namiesto "Žiadne údaje nie sú odosielané cez internet" napisat "Údaje ktoré zadávate do tohoto formulára sa odošlú po vytvorení emailu na adresu Vášho mestského/obecného úradu."
To prve nie je vo svojej podstate a konecnom stave pravdivé :D,  a toto druhe je pridlhe :(

Stale ma trapi to, ze aj ked budu vyriesene problemy #20 a texty a tlacitka budu jednoznacne, bude pre niektorych tazke nezabudnut a najst a prilozit na mobile pdf prilohu. Pre istotu by som v GA sledoval pokial sa dostali. Len to mi nic o odoslani emailu nepovie...

**Comment by ujovlado** [comment]
Toto by sa podla mna dalo vyriesit jednoducho. Vyhodit toto upozornenie z formularov a len do "footra" na uvodnej stranke by sa dala hlaska, ze:

> Tato aplikacia funguje vo Vasom prehliadaci, ziadne osobne udaje nie su posielane cez internet.

**Comment by scholtz** [comment]
link na readme do gitu hadam bude stacit.. ak chcete nazvat tie "dodatocne informacie" nejako lepsim prekladom vyrazu "disclaimer" tak dajte navrh..
