### ISSUE TITLE
PDF sa na W7 FF generuje zbytočne 2x a na Androide v Sony vstavanom prehliadači vôbec.

### ISSUE THREAD

**Issue by roman3x** [marsher/volby-zo-zahranicia#20]
Win 7, firefox: "Vytvorit nahlad ziadosti" v prehliadaci mi vygeneruje pdf k stiahnutiu aj ked to nechcem. Neda sa to bez toho? Potom sa mozem zbytocne zamyslat, co s tym: http://i.imgur.com/jYyo0gr.gifv  Rovnako aj stiahnut pdf mi ho vygeneruje 2x. 
Predpokladam, ze vo formulari je odkaz na neexistujuci obrazok a preto to ff robi. Mozno to prestane robit, ked sa odstrani niekde tu spomenuty bud "donacitavania". Mozno to vsak robi chybajuca/navyse hlavicka pdf dokumentu.

**Comment by roman3x** [comment]
Lepsie povediac aj prve, aj druhe pdf sa mi v ff win 7 vygenerovalo 2x. "Vytvorit nahlad ziadosti" v prehliadaci vygeneruje pdf aj ked to nechcem. Potom sa mozem zbytocne zamyslat, co s tym. :)

**Comment by roman3x** [comment]
Android 4.1 Sony experia E
- Vstavany browser prve pdf negeneruje, co ma netrapi :), ale druhe stahuje "nekonecne dlho". Mozno preto, ze ho stahuje bez nazvu suboru. 
- Google Chrome chce prve pdf stahovat 2x (Travolta by neodvolil) a druhe stahuje korektne pri jednom kliku iba 1x. 
  Scasti pomoct by mohlo najst v API pomenovat subor, pretoze v Chrome ho pomenuje asi automaticky stiahnuť.pdf, kdezto vstavany to nevie. 

https://datatables.net/extensions/buttons/examples/html5/filename.html

**Comment by roman3x** [comment]
Opera na androide 4.1 tiez blbne. moc by som ju neriesil a mozno sa sfunkcni sfunkcnenim Chrome. 

Nebude lepsie pdf cast pouzit z https://www.facebook.com/michal.truban/posts/10206974380733843?comment_id=10206978814284679 ?

**Comment by scholtz** [comment]
túto issue zavriem, a vytvorím novú s podporou zariadení..
