### ISSUE TITLE
uprava velkosti riadkov v pdf, keby chcel niekto rucne

### ISSUE THREAD

**Issue by mtruban** [marsher/volby-zo-zahranicia#21]
Mozte generovat pdfko s vacsimi riadkami tak, aby bolo mozne pohodlne dopisat udaje rukou? Napriklad ked zaujemca nechce, aby jeho/jej rodne cislo bolo v databaze.

**Comment by scholtz** [comment]
ak nechce zadat rodne cislo, tak neh ho nevyplni, a na prazdne miesto doplni rukou text..
