### ISSUE TITLE
Pouzitelnost nazvu stiahnuteho pdf

### ISSUE THREAD

**Issue by roman3x** [marsher/volby-zo-zahranicia#23]
- Rodne cislo sa nekontroluje, co nechcem buzerovat, alebo chvalit JS, ze to dokaze, ale ak by kvoli chybajucej cifre z RC, alebo preklepu mali odmietnut ziadost, bola by to skoda. 
- Dokument sa mi stiahne ako OCWxaA22.pdf. ..... :D No pridavaj uzivatelovi robotu hladanim hashu na disku pokial sa tam nepreklikne z prehliadaca zo stiahnutych dokumentov.

**Comment by roman3x** [comment]
"Pouzit" (podpis) a vsetky tlacitka typu dalej by mali byt asi na jednej strane. Zjednotene. Podla mna na pravej.

**Comment by pavolgal** [comment]
validacia RC tu:
https://github.com/marsher/volby-zo-zahranicia/pull/81

**Comment by roman3x** [comment]
Tato nepouzitelnost nazvy dokumentu je vo svojej podstate zrejme bug #20

**Comment by scholtz** [comment]
nazov suboru je nastaveny na zidost-o-hlasovaci-preukaz.pdf alebo zidost-o-voblu-postou.pdf .. viete skontrolovat ci to funguje?

**Comment by pavolgal** [comment]
funguje, akurat tam mas preklep - voblu

**Comment by roman3x** [comment]
Win 7, posledny FF stiahne ako predtym na 2x, prvy krat 8 znakovy hash a az druhy krat so zvolenym nazvom. To iste Android 4.1 Chrome. Vstavany default Sony prestal fungovat. Opera uz stahuje prve pdf so starym nazov. U nej konkretne default.pdf. Ale dalej sa nedostanem.

**Comment by scholtz** [comment]
Win 7, posledny FF stiahne ako predtym na 2x to co znamena? 

som myslel ze na windowsoch to normalne funguje..

@pavolgal dik za opravu..

**Comment by roman3x** [comment]
Ked sa opravi ta JS & noIOS zariadenie chyba ( https://github.com/marsher/volby-zo-zahranicia/issues/108#issuecomment-164583571 ), tak to skusim este s vypnutym adblockom. 
Ale pred opravou to stiahlo BEZ OPYTANIA 2x 2 tie iste subory s inym nazvom/hashom aj v pripade nahladu a aj v pripade pred poslatim emailu.

**Comment by roman3x** [comment]
@scholtz Ako som pisal vyssie - kliknutim na generovat nahlad mi forsne subor na stiahnutie s hashovym nazovm. Pri naslednom kliku mi uz stiahne s nazvom. Tak aj na generovani pred poslatim emailu.

**Comment by scholtz** [comment]
"kliknutim na generovat nahlad mi forsne subor na stiahnutie s hashovym nazovm. Pri naslednom kliku mi uz stiahne s nazvom" to robi pod akym os/browserom? (to znamena asi ze nastavenie pdfka do iframu nefunguje, tak by sme to na tom os/browsri mohli vypnut a nechat iba tlacitko..)

**Comment by roman3x** [comment]
Videl som to teraz na inom Win 7/FF a uplne super. Tak mam asi ja problem. Mohli by aj ini useri s FF napisat, ako im to funguje pls.
