### ISSUE TITLE
meta data pre socialne siete

### ISSUE THREAD

**Issue by mtruban** [marsher/volby-zo-zahranicia#25]
ked sa to bude sharovat, nech to pekne vyzera...

**Comment by ondrek** [comment]
partially done — treba pridat poriadne obrazky, zatial je tam len logo

**Comment by mtruban** [comment]
zislo by sa dat tento obrazok tam:
https://www.dropbox.com/s/ngy7m196mhlbquz/facebook_share_volby.png?dl=0

**Comment by s7anley** [comment]
@scholtz ho pridal v dc52d93f543ba2b519b8ab94893b521f57a1c8eb. Čo teda ešte chýba?

**Comment by mtruban** [comment]
nefunguje to. resp. facebook to netaha.

**Comment by s7anley** [comment]
@mtruban bolo to iba zacachované, už by sa tam mal obajaviť správny obrázok

**Comment by mtruban** [comment]
dik. done

**Comment by roman3x** [comment]
Do obrazku pridat aj info o volbe z inej volebnej miestnosti, kedze to tam tiez je?

Asi do obrazku by som aj uplne hore pridal "V čase volieb nebudete v mieste svojho trvalého bydliska?"

Text "Pripravte si žiadosť cez telefón a bez čítačky. Stačí Vám adresa a rodné číslo.." by som zmenil na:
"Požiadajte teraz o možnosť voliť zo zahraničia, alebo kdekoľvek na Slovensku, kde budete v čase volieb. Stačí Vám adresa a rodné číslo."
