### ISSUE TITLE
Navbar pri mobile view

### ISSUE THREAD

**Issue by przno** [marsher/volby-zo-zahranicia#27]
Horny navbar je trocha rozbity ked stranku otvorim v mobile.
Screen z mobilu:
![2015-12-10 20 12 04](https://cloud.githubusercontent.com/assets/8056561/11727278/432d1cb4-9f83-11e5-9fc2-660580633e33.png)

Emulovany mobile view v browseri na pc:
![emul_pc](https://cloud.githubusercontent.com/assets/8056561/11727292/5e9c3836-9f83-11e5-8de8-8499fdbadd7e.PNG)

**Comment by peterkracik** [comment]
#41

**Comment by s7anley** [comment]
@przno môžeš potvrdiť, že je to už v poriadku?

**Comment by roman3x** [comment]
Na 480 x 320px displayi na 3 prehliadacoch tam nevidim prvy riadok. Napr. "V čase volieb budem mimo Slovenska" mam rozdelene na 2 riadky, co nie je problem, ale z prveho vidim iba spodnych 10% textu, cize neprecitam. Je pod hlavickou.

**Comment by przno** [comment]
U mna OK

**Comment by roman3x** [comment]
u Teba to je na akom displayi? Ale ak sa povie, ze stare sumky nepodporujeme, tak ok. Ale ak podporujeme, tak ak by som nevedel, co je v hornom riadku, tak netusim a mozem sa zle rozhodnut.

**Comment by przno** [comment]
aha, mohol som napisat - galaxy s3, 720 x 1280px.

**Comment by roman3x** [comment]
Na Android 4.1 zariadeni s 480 x 320px stale vidim z horneho informacneho riadku ( napr "Adresa Vášho trvalého pobytu" ) v Opere 2px a Vstavanom prehliadaci 5px. Ak neratam fajky pismen pod riadkom. Google ok, az vela.

**Comment by ujovlado** [comment]
@roman3x v aktualnom mastri by to uz malo byt ok, vies to overit?

**Comment by roman3x** [comment]
Ano, uz to je pekne vo vsetkych 3. :+1:
