### ISSUE TITLE
upgrade posledneho kroku

### ISSUE THREAD

**Issue by mtruban** [marsher/volby-zo-zahranicia#28]
- mailto: nefunguje 100% na vsetkych platformach a ludia nemusia mat zapnutych klientov.

button ODOSLAT, resp. POSLEDNY KROK treba nahradit niecim takymto:

teraz poslite mail na adresu: XX@XX.com - vybera sa z DB 
s predmetom:
a s telom textu:
a s prilohou : — LINK — 

(alebo ak mate aktivovaneho mailoveho klienta, vyskusajte to odoslat automaticky.. <- a to bude ten link na mailto: + auto download vyplnenej ziadosti
- zaverecna thank you obrazovka s dalsimi krokmi, ktore treba spravit. (overti si, ci ziadost dosla.. atd...)

**Comment by scholtz** [comment]
urobil som to, ak to chcete niekto este upravit, tak to skontrolujte..

alebo mozte issue pripadne zavriet..

**Comment by mtruban** [comment]
zatim OK. este nejake graficke upgrady bude treba. ale to dam do inej issue.

**Comment by roman3x** [comment]
Podla mna je to degradacia celeho projektu. Tam by malo byt prave tlacitko na odoslanie cez serverovu mail funkciu. Aspon v pripade, ak sa da overit navratova funkcia z mailto. Ale to by muselo bezat na https & info o tom, ze osobne udaje nebudu uchovavane. Co neviem, ci bude stacit. 
Ked je tam teraz krok 7/6, chyba tam navrat na predchadzajucu stranku, ked si to chcem stiahnut.

**Comment by mtruban** [comment]
- rozhodli sme sa na server neposielat nic... zasa uz si ten mail naklikas sam a stale tam mas ten button. ukladanie udajov ti nemusi nikto verit.
- k tomu chybajucemu spat dam dalsie issue.

**Comment by kaqpa** [comment]
Pri odosielani na ministerstvo (pokial clovek nema trvaly pobyt na SK) tam este nie su udaje
<img width="300" alt="screen shot 2015-12-10 at 18 26 19" src="https://cloud.githubusercontent.com/assets/8911929/11732635/b62be5aa-9f6b-11e5-9420-e6a7bd0438df.png">

**Comment by roman3x** [comment]
Neda sa odkliknut aj pridanie notifikacie do kalendara? Ak by som zabudol, ked mi od nich nic nepride. Podla moznosti aj s tlf cislom.
