### ISSUE TITLE
BUG - mesto nahradene na cislo do pdf

### ISSUE THREAD

**Issue by mtruban** [marsher/volby-zo-zahranicia#30]
Vo formulare http://volby.digital mate zrejme bug.
Miesto nazvu mesta to do .pdf tlaci cislo..

**Comment by scholtz** [comment]
ja toto neviem replikovat, bud je to uz fixnute, alebo sa to stava v specialnych pripadoch..

Pri akom meste to je?

**Comment by mtruban** [comment]
skusim zistit. to reportoval typek, na ktoreho nemam kontakt. zatim asiq nechat tak

**Comment by kubocob** [comment]
Ja to mam reprodukovatelne. Po refreshi - bez zmien/vracania sa spat a pod, vybrane prve mesto - ktore je uvedene v hlavicke.
![image](https://cloud.githubusercontent.com/assets/7217565/11728816/4ef69d78-9f8c-11e5-8180-c446cca83057.png)

**Comment by kubocob** [comment]
pouzita hodnota z PDF je ulozena v 

``` javascript
$('#addressslovakia-city').val() // tu je ale len ID
```

treba ju v nastavObec niekam ulozit (tak ako sa ukladaju

``` javascript
$("#adresa").val(adresa);
$("#addressslovakia-zip").val(o[ico][4]);
```

napriklad:

``` javascript
$("#addressslovakia-cityName").val(o[ico][5]); // EDIT: na piatom indexi je myslim nazov mesta
```
