### ISSUE TITLE
Dokumenty pre volby zo zahranicia bez trvaleho pobytu.

### ISSUE THREAD

**Issue by peterppp** [marsher/volby-zo-zahranicia#31]
Momentalne su tam dva dokumenty: Ziadost a Prehlasenie. Toto treba zlucit do jedneho dokumentu - bolo to odskusane a minv.sk to akceptovalo.

Tu je text:

[WNR16_3311 upravene.pdf](https://github.com/marsher/volby-zo-zahranicia/files/58727/WNR16_3311.upravene.pdf)

ŽIADOSŤ VYPLŇTE VEĽKÝMI PÍSMENAMI.
Žiadosť o voľbu poštou
pre voľby do Národnej rady Slovenskej republiky v roku 2016 
a čestné vyhlásenie

Ministerstvo vnútra Slovenskej republiky 
odbor volieb, referenda a politických strán
Drieňová 22
826 86  Bratislava 29
SLOVAK REPUBLIC
volby@minv.sk

Čestne vyhlasujem, že nemám trvalý pobyt na území Slovenskej republiky.

Podľa   § 59 ods. 1   zákona   č. 180/2014 Z. z. o podmienkach výkonu volebného práva a o zmene a doplnení niektorých zákonov žiadam o voľbu poštou pre voľby do Národnej rady Slovenskej republiky v roku 2016 a o zaslanie hlasovacích lístkov a obálok na adresu:

Meno:   

Priezvisko: 

Rodné priezvisko:  

Rodné číslo: 
Ulica:  

Číslo domu:   

Obec:   

PSČ:   

Štát: 

V           

Dátum:  
Podpis: 

Prílohy:
-   fotokópia časti cestovného dokladu Slovenskej republiky s osobnými údajmi voliča
  alebo fotokópia osvedčenia o štátnom občianstve Slovenskej republiky voliča.

**Comment by scholtz** [comment]
to prehlasenie je na druhej strane toho PDFka.. aj podpisana.. tak myslim ze by to mohlo byt vpohode tak ako je to teraz.. ci?

**Comment by peterppp** [comment]
ziadost aj prehlasenie by sa mali obe rucne podpisat. Automaticke kopirovanie podpisu na dve ziadosti nie je legalne v poriadku.
A hlavne to ani nemusime robit - ta skombinovana ziadost a prehlasenie boli akceptovane. Takze asi by som pouzil to. Takto nam bude stacit jeden podpis

**Comment by scholtz** [comment]
ma to inu mierku.. aj to nie je legalne? :)

**Comment by peterppp** [comment]
na mierke nezalezi. Ta ziadost moze byt napisana aj rukou. Ale tie dve ziadosti treba zlucit do jednej. Je to jednduchsie a menej roboty.

**Comment by peterppp** [comment]
toto este nebolo upravene. Prosim nahradit tie dve PDFka jednym takymto:
[WNR16_3311 upravene.pdf](https://github.com/marsher/volby-zo-zahranicia/files/60432/WNR16_3311.upravene.pdf)

**Comment by roman3x** [comment]
@peterppp https://github.com/marsher/volby-zo-zahranicia/files/58727/WNR16_3311.upravene.pdf mas od kial? Z ministerstva, ci na kolene zbuchane? :)
