### ISSUE TITLE
ŽIADOSŤ VYPLŇTE VEĽKÝMI PÍSMENAMI

### ISSUE THREAD

**Issue by peterppp** [marsher/volby-zo-zahranicia#32]
ŽIADOSŤ VYPLŇTE VEĽKÝMI PÍSMENAMI. Treba upravit to generovanie PDF aby sa to vyplnalo velkymi pismenami (tak ako je to pozadovane v ziadosti)

**Comment by mtruban** [comment]
treba nakodit, nech automaticky opravuje male pismena na velke.

**Comment by peterppp** [comment]
presne

**Comment by scholtz** [comment]
otazka je, ci tie velke pismenka neboli urcene pre ludi co to chceli pisat rucne.. naco to tam je?

**Comment by scholtz** [comment]
a preco je to iba v jednom type formulara? :)

**Comment by peterppp** [comment]
V druhom tety asi zabudli napisat :)
