### ISSUE TITLE
bug - podpis zhodi prehliadac

### ISSUE THREAD

**Issue by peterppp** [marsher/volby-zo-zahranicia#33]
ked idem:
Pripravit Ziadost > Odhalseny > Vytvorit Nahlad > Podpis
a podpisem sa tak mi to zhodi cely prehliadac (iPhone 4S Safari na iOS7)

**Comment by scholtz** [comment]
Chcelo by to viac testerov, ale mne to vyzera skor ako bug safari..

**Comment by scholtz** [comment]
tak co, niekomu sa to podarilo replikovat? este stale sa to stava?

**Comment by s7anley** [comment]
Safari iOS8.4.1 na 4S v pohode.

**Comment by peterppp** [comment]
uz to funguje aj na iOS 7.1.2 na 4S

**Comment by peterppp** [comment]
mozme zatvorit
