### ISSUE TITLE
Databaza e-mailovych adries / kontaktov. Overenie e-mailov

### ISSUE THREAD

**Issue by peterppp** [marsher/volby-zo-zahranicia#35]
mame zakupenu databazu od e-Obce (bolo tam 58 obci bez e-mailu)
Dodatocne sa podarilo ziskat cca 30 e-mailov.
Treba zlucit tieto databazy do jednej.

Bude nutne skontrolovat e-maily na ktore sa to bude posielat.

**Comment by roman3x** [comment]
Povazska Bystrica ma najcastejsie PSC 017 01 a nie 017 13

**Comment by scholtz** [comment]
Pravda. Oficialna stranka hovori ze psc je 017 01..  http://www.povazska-bystrica.sk/kontakt.phtml?id3=2258

**Comment by scholtz** [comment]
psc povazskej bystrice bolo opravene, otazne je ci zavriet tento thread, alebo to niekto blizsie bude studovat ci tam nie je viac podobnych chyb..

**Comment by scholtz** [comment]
DB bola mergnuta s aktualnymi udajmi. Je niekto kto chce/vie skontrolovat emaily obci?

**Comment by roman3x** [comment]
Tak sa ospravedlnujem. Niektore vacsie organizacie mozu mat vlastne PSC a mestsky urad v PB je jedna z nich. https://www.podnikajte.sk/strankove-hodiny/uradu/mestsky-urad-povazska-bystrica.xhtml 
Cize 017 13 bolo spravne. Mesta mavaju vacsinou 01 na konci a obce ine cislo, ale su aj vynimky pre urychlenie triedenia na poste. Posta to doruci, akurat jej to automat asi sam nepriradi do P.O.Boxu pre MSU. 
V online databaze http://psc.posta.sk/ to nenajdeme, ale v suboroch v  http://www.posta.sk/subory/322/psc-obci-a-ulic.zip je k pouzitiu.

**Comment by scholtz** [comment]
urcite? podla oficialnej stranky mesta je podatelna tu:

Mestský úrad Považská Bystrica
Adresa: Centrum 2/3, 017 01 Považská Bystrica
spojovateľ, podateľňa - tel: 042/4305111

**Comment by roman3x** [comment]
Teraz som sa tam už nedovolal, ale zistím v pondelok, pretože:
- Mesto má 01701
- Mestský úrad 01713
  :dancer: 
  http://www2.uvo.gov.sk/evestnik/-/vestnik/162262

**Comment by peterppp** [comment]
Skontroloval som prvych 50 miest (podla velkosti)

**Comment by peterppp** [comment]
Myslim ze pole PSC by malo byt volne pre uzivatela.
Ta databaza PSC co mame obsahuje PSC na urady a nie na mesto.
Takze PSC pouzijeme z databazy na generovanie adresy uradu ALE nechame prazdne policko PSC pri sukromnej adrese aby si to mohol uzivatel vyplnit sam.

Tiez by som asi nechal prazdne policko pre OBEC na vyplnenie. Casto su to mensie obce co maju zlucene urady ale adresa obcana moze byt v inej obci. Napriklad ak byvate v obci Hurbanovce tak vas obecny urad je v obci Dedinka.

Dufam ze to dava zmysel. Toto je dolezite.

**Comment by scholtz** [comment]
suhlas, psc je uz opravene..

**Comment by scholtz** [comment]
Cau @roman3x , poslednou upravou db sa odstranilo asi viac emailov ako sa malo.. 

npr: 
hurbanova.ves@zoznam.sk;hurbanova.ves@azet.sk > hurbanova.ves@azet.sk
dalej domena by mohla byt asi preferovana viac ako prva cast emailu..
info@dolnamicina.sk > obecdolna.micina@mail.t-com.sk

pozries sa prosim na to?

**Comment by roman3x** [comment]
Obce, ktore maju viac rovnocennych emailov typu zoznam/azet/gmail mam zachovat vsetky emaily?

**Comment by scholtz** [comment]
novy update vyzera pekne..

**Comment by scholtz** [comment]
pre informaciu, na vsetky emaily co mame bude odoslany email aby nam zadali email kde sa to ma odoslat..

**Comment by roman3x** [comment]
Rozmyslam, ci by sme nemali uchranit prijemcov na adrese volby@presov.sk od spamov z "testovacov" formularov, ze ked sa nevyplni vsetko, tak sa ziadny email neodosle. Alebo nebudeme taki privetivy a Kraj/Okres/Obec bude treba v kazdom pripade vyplnit?

**Comment by scholtz** [comment]
aby niekto pokracoval v odosielani emailu aj mimo prehliadaca musi robit poriadny test.. :)

a takych testov hadam vela nebude, takze nema velky zmysel sa tym zaoberat..

**Comment by roman3x** [comment]
> pre informaciu, na vsetky emaily co mame bude odoslany email aby nam zadali email kde sa to ma odoslat..
> Toto je v akom stave? Nepatrilo by sa rovno na ministerstvo napisat, ci nemaju emailove adresy obci, ktore maju emailove adresy k tomu sluziace? 

Diskusia na fb DennikN:
- odpisali mi z Kosic: "Magistrát mesta Košice nevybavuje túto agendu, preto Vám odporúčam kontaktovať priamo miestny úrad mestskej časti, v ktorej máte trvalý pobyt.".... cize zase volat, pisat, hladat toho spravneho uradnika, etc....

**Comment by roman3x** [comment]
Asi viete k tomu viac ako tu citam https://www.facebook.com/michal.truban/posts/10206974380733843?comment_id=10207004032955130

**Comment by scholtz** [comment]
overenie emailov bolo zahrnute a implementovane. overeny email sa zobrazuje ze bol overeny. zatial je to na teste

mozem tuto issue uzavriet?

**Comment by roman3x** [comment]
Vzhľadom na paniku, ktorá bola vyvolaná v RTVS reportáži údajnou nefunkčnosťou pre neoverené emailové adresy by bolo vhodné niekde dať vedieť, že z 2927 obcí má NAJVäČŠíCH 2814 email(2457 sk +357 com). Z čoho máme 2120 úradmi overených emailov.
