### ISSUE TITLE
texty v buttonoch su podciarknute

### ISSUE THREAD

**Issue by mtruban** [marsher/volby-zo-zahranicia#37]
detail, ale bolo by fajn to dat prec. (chrome, mac)

**Comment by musho** [comment]
to neni bug to je feature :)

**Comment by mtruban** [comment]
hehe. ale vyzera to spatne. aky to ma dovod?

btw, @musHo  o tomto si co myslis? 
https://github.com/marsher/volby-zo-zahranicia/issues/8

**Comment by musho** [comment]
Button bol prebraty z slovensko.digital, nema znamky beznych klikacich veci rounding/gradient, moze to vyzerat len ako zvyrazneny nadpis. Pre niektorych ludi co je podciarknute to je klikatelne. A aby to nebol uplny digitalny socik, tak su svetlejsou farbou.

**Comment by mtruban** [comment]
dik. za vysvetlenie. closujem to issue. ale ten cerveny button ti neodpustim :)
