### ISSUE TITLE
UX - zamena 2 textov

### ISSUE THREAD

**Issue by mtruban** [marsher/volby-zo-zahranicia#38]
tam kde je text v kroku 2, ked vyplnam formular:
Korešpondenčná adresa pre odoslanie hlasovacích lístkov alebo preukazu:

(lebo tu nemusi byt jasne, aka to je presne adresa)

treba zamenit za pochopitelnejsie (co je aj na ziadosti)
Adresa miesta pobytu v cudzine (pre zaslanie hlasovacích lístkov a obálok):

**Comment by mtruban** [comment]
- otazka, netreba tam dat aj meno do tej ziadosti na tu adresu trvaleho pobytu?? dojde to tym uradnikom?

**Comment by kubocob** [comment]
Suhlasim s prvym komentom.
A osobne by som pridal aj meno do korenspondencnej adresy. Ludia nemusia mat vzdy na schankach svoje meno.

**Comment by roman3x** [comment]
Po podpise je "Stiahnut" a "Po ulozeni". Mohlo by byt "1. Ulozit", "2. Po ulozeni". A ak to musim stahovat, tak aj prve tlacitko modre a nie sede.

**Comment by roman3x** [comment]
Niekde asi v meta tagoch treba nastavit slovencinu, lebo v google chrome na androide v bode 1/6 obtazuje s  tym, ze je to v anglictine a ci si to zelam prelozit do slovenciny.
.... mno...ale kto vie v akom jazyku pouziva mobil vacsina zahranicnych slovakov. :)

**Comment by scholtz** [comment]
moze to ostat takto?

**Comment by roman3x** [comment]
Co sa jazyka tyka, tak ok.
