### ISSUE TITLE
chyba krok spat v poslednom kroku

### ISSUE THREAD

**Issue by mtruban** [marsher/volby-zo-zahranicia#40]
Ked je tam teraz krok 7/6, chyba tam navrat na predchadzajucu stranku, ked si to chcem stiahnut.

(v poslednom kroku chyba hore lista)

**Comment by s7anley** [comment]
Iný tiež nefunkčný case: Registrovaný na Slovensku > Chcem hlasovací preukaz > ak následne zvolím hoci ktorú možnosť, tak následne nefunguje "Späť na krok 3".

**Comment by scholtz** [comment]
done
