### ISSUE TITLE
Nefunkcne vyber mesta na android 4.1 v google chrome

### ISSUE THREAD

**Issue by roman3x** [marsher/volby-zo-zahranicia#43]
Ostanu mi tam vybrate Abovce. Vstavany browser ok. Sony Xperia E.

**Comment by scholtz** [comment]
db obci je dost velka, mozno treba iba chvilku pockat po kliknuti na vyber.. 

ak to nepojde koli tomu ze select2 je pomaly, je otazne co tam dat aby sa obce mohli lahko najst..

**Comment by roman3x** [comment]
Teraz sa mi aj podarilo vybrat, odozva dlhsia 1-2 sec po pismene, ale viac ako 50 sec. som nevydrzal cakat na ulozenie najdeneho mesta. :D Vstavany prehliadac no problema.

**Comment by kubocob** [comment]
Ma vyznam vobec renderovat cely zoznam a nie az po napisani 2-3 znakov? Myslim, ze nikto nebude listovat cely zoznam. Tym ziskame lepsiu performance.

**Comment by roman3x** [comment]
super podla mna ako uzivatela, akurat sa prekvapim, ked niekto zmaze znaky az po tie 2-3 a zmizne mu zoznam, alebo sa dogeneruje cely?

**Comment by freezysko** [comment]
@roman3x skusil by som zacat limitom na 1 pismeno a ak to bude stale pomale tak 2 by mali uplne stacit

**Comment by scholtz** [comment]
teraz je najskor vyber kraja, potom okresu a potom obce aby select formular nebol prilis velky.. select2 sa teraz nepouziva a rozmyslam ci ho tam dat alebo nie..

**Comment by scholtz** [comment]
je to ok? mozme zavriet issue?

**Comment by roman3x** [comment]
Fajnejšie to je, ale mohli by sme tým ľuďom ešte o ďalšie 3 sekundy skrátiť výber predvolením lepších krajov, okresov a miest, ako BB a Badína 1900 obyvateľmi. Je pravda, že Badín, ktorý je medzi BB a Zvolenom je asi celkom blízko geografického stredu Slovenska... :D

**Comment by roman3x** [comment]
Ano, je to ok.
