### ISSUE TITLE
Da sa aktivovat mailovy klient aj na iOS/Android??

### ISSUE THREAD

**Issue by peterppp** [marsher/volby-zo-zahranicia#44]
Bolo by fajn ak by sa dal aktivovat mailovy klient na iOS a Android
(Tak ako je to na PC)

**Comment by scholtz** [comment]
na mobile by to (mailto:) malo byt jednoduchsie ako na pc sa mi zda

**Comment by roman3x** [comment]
Mne to funguje na andr. 4.1, ale treba aj upozornenie nech clovek prilozi vygenerovane pdf, kedze sa samo neprilozi. A mozno aj kde ho najde. Som zvedavy, ked mi ho spravne ulozi, ci sa mi ho podari prilozit k emailu.

**Comment by matuspavliscak** [comment]
Do mailto: sa ale neda pridat priloha.

**Comment by scholtz** [comment]
ja som si to otestoval na mobile a vyzera ze to ide..

@matushy Preto je ten flow taky ze ta to nabada aby si si to ulozil najskor na disk a potom po kliknuti na mailto pridal ten subor..
