### ISSUE TITLE
varovanie pre obce kde nie je email

### ISSUE THREAD

**Issue by scholtz** [marsher/volby-zo-zahranicia#46]
existuju obce kde nie je email, pre tieto obce treba uzivatela upozornit ze email nie je dostupny.. otazka je, ci mu mame povolit urobit dokument ked to nema kde odoslat

**Comment by kaqpa** [comment]
IMHO áno a nakoniec ho pekne poprosiť, aby to poslal poštou a namiesto mailu ukázať adresu

[nice to have] príp. mu dať možnosť automaticky pridať odstavec, kde ich poprosí, aby si mail spravili, aby to nabudúce posielať poštou nemusel

**Comment by scholtz** [comment]
@kaqpa dik za tip.. 

moze to ostat takto? Testovanie moze byt pre: Trenciansky kraj, Okres Bánovce nad Bebravou, Obec: Uhrovské Podhradie

**Comment by roman3x** [comment]
Povazska bystrica ma 2 emaily a ani jeden z nich tam nie je. Mam pocit, ze to pred 2 dnami fungovalo.
