### ISSUE TITLE
viac emailov na obec

### ISSUE THREAD

**Issue by scholtz** [marsher/volby-zo-zahranicia#47]
Su obce ktore maju evidovanych viac ako jeden email.. Toto treba skontrolovat a dorobit aby sa vsetko spravne zobrazovalo..

**Comment by branoh** [comment]
Pridal som malý fix pri generovaní pdf-ka pre obce, ktoré majú viac ako jednu emailovú adresu: Replace bodkočiarky za newline. [Pull request #65](https://github.com/marsher/volby-zo-zahranicia/pull/65)
Predtým:

![screen shot 2015-12-11 at 11 56 49](https://cloud.githubusercontent.com/assets/2119370/11742322/4051700e-9fff-11e5-9c6c-506e8d367b9e.png)

Potom:

![screen shot 2015-12-11 at 11 53 27](https://cloud.githubusercontent.com/assets/2119370/11742334/500637e6-9fff-11e5-8373-cec9841772fa.png)

Ďalšia otázka ešte je, či niečo robiť s tým ako sú ďalej zobrazené emaily v kroku č. 7.
A ešte je asi možné, že sa nájde prehliadač, ktorý nebude podporovať vytvorenie emailu na viac adries zadaných v `mailto:mail@example.sk;mail2@example.sk?...`):

![screen shot 2015-12-11 at 11 54 12](https://cloud.githubusercontent.com/assets/2119370/11742368/a6211cc2-9fff-11e5-8bb1-e786399a914e.png)

**Comment by scholtz** [comment]
mailto na viac adries by mohol fungovat.. ale to nahradzovanie dako nie je asi pre cely vyraz.. viz npr banska bystrica..

**Comment by peterppp** [comment]
Rozmyslal som nad tymto a myslim ze budeme musiet spravit nasledovne;
1) zoradit obce podla poctu obyvatelstva. Skontrolovat manualne e-mailove adresy na najvacsich 50 alebo 100 obciach. Pocitam, ze tychto 100 obci pokryva 75% obyvatelstva. Tie vacsie obce budu mat aj vyclenenu e-mailovu adresu specialne na ziadosti. Nieco ako volby@nitra.sk a pod..
Nema zmysel v tychto velkych obciach posielat ziadost na 3-4e-maily. Tiez nechceme aby tie e-maily isli nejakej uctovnicke alebo na vratnicu..
Mensie obce budu mat adresu jednu alebo dve..
2) zvysok manualne pretriedit na jednu adresu.
ziadosti budeme posielat na obecnu adresu a nie starostovi

**Comment by roman3x** [comment]
Moc som nepochopil, preco vyhadzujete email na starostu atd zo zoznamu. Osobne by som to riesil najprv presrotenim celeho zoznamu emailov a hladal v nom preferencne. Vid pole $aPreferableEmails. Tie zotriedil podla predpokladane hodnotnejsieho pre nase ucely a prve poslal. Pokial nie je ziadny email hodnotny, az vtedy poslat vsetky. Ked som pouzival aj "starosta", "starostka", ostalo iba 88 obci s viac emailami typu:
"pokladna@klokocov.sk;kontrola@klokocov.sk;dane@klokocov.sk;uctaren@klokocov.sk;pam@klokocov.sk;majetok@klokocov.sk"
"kobylnice@thelocalchannel.co.uk"
Z coho este mozeme automaticky vybrat emaily NAZOVOBCE@DOMENA. Tak druhy parameter do funkcie este nazo obce ktorej dobry email hladame.

``` php
$aPreferableEmails = array( 'podatelna','info','sekretariat','obec','ocu','ou','starosta','starostka'); 

function get_relevant_email($emails){
    global $aPreferableEmails;

    $bestEmails = array();

    if(count($emails) != 1){
        foreach( $emails as $email ){
            $em = explode( '@', $email, 2);

            if( in_array($em[0], $aPreferableEmails) ){
                $bestEmails[ array_search($em[0], $aPreferableEmails) ] = $email;
            }
        }

        if( $bestEmails ){
            ksort($bestEmails);

            return reset($bestEmails);
        }
    }

    return implode(";",$emails);
}
```

**Comment by peterppp** [comment]
super. Ja som to robil manualne zopar hodin vcera :(

**Comment by peterppp** [comment]
Nalepsie je mat iba jeden e-mail. Idealne nechceme posielat viac ako dva e-maily na hociktoru obec.
Posledna verzia zoznamu (rucne triedena) bola spracovana nasledovne:
Prvych 120 obci bolo skontrolovanych rucne - s kontrolou na ich weboch
Dalsie obce boli triedene podla: 
podatelna@obec.sk
obec@obec.sk
msu@obec.sk
starosta@obec.sk
sekretariat@obec.sk

potom tam zostal kopec adries co su na vseliakych gmail.com, zoznam.sk a pod..
Ak by si to vedel prebehnut este raz cez tvoj system tak by to bolo fajn

**Comment by roman3x** [comment]
Bude, ako si zelas, len pockam na vyjadrenie majstra kodu :) a tych ~90 Ti ostane na rucne dorobenie.

**Comment by roman3x** [comment]
Podla nizsie uvedenych zoznamov predvolenych, zakazanych emailov sa dane pouziju/nepouziju. V tretom zozname je slovo, podla ktoreho sa bude urocovat priorita emailu. Emaily s nazvom obce za @ maju vyssiu prioritu. Ak su preferencne emaily, vyberie sa iba jeden. Ak nie. vyberu sa vsetky (1-3).

Nepatral som, ci po pulle bude treba spustit spracuj, alebo to urobi cron, ...

Nasledne ostalo ~10 obci:

```
vapenik: pajkos.pe@gmail.com;peter_pajkos@centrum.sk
gemerske-dechtare: gm.dechtare@stonline.sk;gm.dechtare@mail.t-com.sk;zagyis@mail.t-com.sk
ruska: imrich.lakatos73@gmail.com;idoboruszka@gmail.com
ipelske-predmostie: ipelpred@gmail.com;ipelpred@inMail.sk
tekovske-luzany: luzany@nextra.sk;tekluzany@gmail.com
mala-domasa: mdomasa@gmail.com;jaro.makatura@gmail.com
potonske-luky: potluky@post.sk;alajosrostas@centrum.sk
vojcice: vojcice1@gbs.eu.sk;vojcice2@gbs.eu.sk;vojcice3@gbs.eu.sk
```

Dalsie obce, alebo zmenu pravidla preferencnosti by si tam vedel doprogramovat uz aj TY. :) v subore https://github.com/marsher/volby-zo-zahranicia/blob/master/spracuj.php

``` php
$aForcedEmails = array('starostka@karlovaves.sk','radnica@mestosnv.sk','kravany@kravany.com','');//bude priradeny iba jediny pre obec
$aDisabledEmails = array('daniel.juracek@bosaca.eu','obec.bartosovce@wi-net.sk','oubenice@gaya.sk','betlanovce@stonline.sk','oub.kostol@apo.sk','dusan.zeliznak@gmail.com','obecboliarov@netkosice.sk','oubajtava@mail.t-com.sk','babindol@babindol.sk','peter.nemecek@obecbab.sk');
$aPreferableEmailParts = array( 'podatelna','obec', 'ocu', 'ou', 'obu', 'urad', 'mu','msu','mesto','sekretariat','kancelaria','obecnyurad','miestnyurad','mestskyyurad','info','referent','NAZOVOBCE@NAZOVOBCE.SK','@NAZOVOBCE.SK','NAZOVOBCE','NAZOVOBCE@','primator','primatorka','starosta','starostka','kancelariaprimatora','prednosta','prednostka'); 
```

**Comment by roman3x** [comment]
Neviem, ci sa mozeme tesit z takeho kratkeho zoznamu, lebo ako pise @scholtz v https://github.com/marsher/volby-zo-zahranicia/issues/35#issuecomment-164404542 tak zo zoznamu vypadla druha adresa pre hurbanova.ves@zoznam.sk;hurbanova.ves@azet.sk > hurbanova.ves@azet.sk
Ked tam naslo aspon 1x nieco z preferovaneho zoznamu, cize v tomto pripade NAZOVOBCE@ tak tomu priradilo vyssiu prioritu a vaznost a nevratilo druhy email. 
Co ty na to @peterppp, nemal by som Ti vytvorit zoznam vsetkych takychto obci/emailov, nech rozhodnes/te?

**Comment by scholtz** [comment]
ja som urobil este dalsi filter kde sa priraduje vaha kazdemu emailu a podla tej vahy sa to triedi a vybera najlepsi.. 
mozno by sme mohli urobit este nieco ze ked sa vaha nenazbiera aspon na nejaku uroven (teda nie je email ako podatelna@... ) tak by sa to poslalo na vsetky emaily..

**Comment by roman3x** [comment]
Mozno Ta zmiatol bug, ktory som tam mal rano a cez ktory to nepreslo, ale toto je kratsie riesnie. :) Takze veci ohladom 

``` php
$bestEmailsWithDomain = array();
$bestEmails = array();
$t
```

mozem/e asi vyhodit. Nic sa nedostalo za Tvoj novy foreach. :D A aj z pola $aPreferableEmailParts vyhodit prvky okolo NAZOVOBCE.

Uroven o ktorej pises je asi 1, pretoze Vapenik, ktory je z tych 10 chabych emailov do toho pasuje a ma taketo urovne:

```
array(2) {
  ["peter_pajkos@centrum.sk"]=>
  int(0)
  ["pajkos.pe@gmail.com"]=>
  int(0)
}
```

Spadnu do toho tie iste mesta, ako u mna, akurat emaily v inom poradi. :) 

```
vapenik: peter_pajkos@centrum.sk;pajkos.pe@gmail.com
gemerske-dechtare: zagyis@mail.t-com.sk;gm.dechtare@mail.t-com.sk;gm.dechtare@stonline.sk
ruska: idoboruszka@gmail.com;imrich.lakatos73@gmail.com
ipelske-predmostie: ipelpred@inMail.sk;ipelpred@gmail.com
tekovske-luzany: tekluzany@gmail.com;luzany@nextra.sk
mala-domasa: jaro.makatura@gmail.com;mdomasa@gmail.com
potonske-luky: alajosrostas@centrum.sk;potluky@post.sk
vojcice: vojcice3@gbs.eu.sk;vojcice2@gbs.eu.sk;vojcice1@gbs.eu.sk
bodruzal: dusan.zeliznak@gmail.com;ZeliP@zoznam.sk
```

Ziadne ine podla mna netreba riesit. Posielal by som max. na 2 emaily, ale iba jedno z nich ma 3 emaily, tak sa trapit nemusime.

**Comment by roman3x** [comment]
@peterppp tu https://github.com/marsher/volby-zo-zahranicia/pull/109#issuecomment-164476410 mas prehlad, kedy to bude davat viac emailov na obec. mozeme tam mat posielanie na viac emailov iba pre tych 8 emailov co uz som vyssie pisal, alebo pre viac. Co Ty na to?
Tak isto moze @scholtz v emaili, ktory sa zasle na viac emailov pripisat uradu, nech nam daju na daky email vediet, ktory je ten spravny.

**Comment by scholtz** [comment]
mas pravdu, sorry sa mi nesyncol subor.. na webe je nova db

**Comment by scholtz** [comment]
mozme tuto issue zavriet?

**Comment by roman3x** [comment]
Podla mna ano. Aj ked sa @peterppp nevyjadril.
