### ISSUE TITLE
Mailto 

### ISSUE THREAD

**Issue by marsher** [marsher/volby-zo-zahranicia#5]
Pridat mailto button, s vygenerovanim attachmentov

**Comment by filiplikavcan** [comment]
Ahoj. Uz mate vymyslene ako to robit? Ak treba pomozem a spravim research.

**Comment by filiplikavcan** [comment]
Jeden napad: Posielat to priamo z klienta: http://emailjs.org/ Nevyhoda: musel by sa spravit account na SMTP serveri, cez ktory by sa to posielalo, co by defacto znamenalo, ze user posiela email cez server tretej strany.

**Comment by marsher** [comment]
Ahoj. povodne som mal pocit ze mailto attachment podporuje, bohuzial to tak nieje ( https://www.ietf.org/rfc/rfc2368.txt ) Rozhodne nechceme posielat data cez server, preto momentalny plan je, ze uzivatel si PDFko sam stiahne a prida attachment.

Samozrejme z UX hladiska som otvoreny napadom, ale nemyslim ze toto client-side pojde.

**Comment by peterppp** [comment]
suhlasim s marsher > Nechceme sa prenosu osobnych dat dotknut
