### ISSUE TITLE
Text z 1. tlačítka prechádza do druhého (krok 3)

### ISSUE THREAD

**Issue by kaqpa** [marsher/volby-zo-zahranicia#51]
OSX 10.11
Safari 9.0
Chrome v46.0

<img width="515" alt="screen shot 2015-12-10 at 18 38 52" src="https://cloud.githubusercontent.com/assets/8911929/11732904/80bb0592-9f6e-11e5-91f4-89855f8cbaee.png">

**Comment by marsher** [comment]
To iste sa stava na viacerych buttonoch na mobilnych screenoch

**Comment by marsher** [comment]
#58 to opravuje
