### ISSUE TITLE
Ked napisem cele mesto dostanem JS error

### ISSUE THREAD

**Issue by babjatom** [marsher/volby-zo-zahranicia#55]
Napisal som cele mesto 'Michalovce' a potom to odo mna chce aby som na michalovce klikol pre vyber.
Potom dotanem nasledujuci js error:

![bug](https://cloud.githubusercontent.com/assets/3949197/11735427/aec53ffe-9ff3-11e5-88fb-923ab5b0fe5a.png)

**Comment by s7anley** [comment]
Bude opravené v #52 alebo #53. Podľa toho, ktoré sa vymerguje.

**Comment by marsher** [comment]
Fixnute v #52 , zatvaram.
