### ISSUE TITLE
Databaza - navigacia

### ISSUE THREAD

**Issue by peterppp** [marsher/volby-zo-zahranicia#63]
Skusal som v telefone zvolit z menu nejaku obec z konca zoznamu. Trvalo to velmi dlho sa prerolovat az na koniec - skuste si to niekto otestovat na telefone. Napriklad taku Zilinu.

Mozno by sme mali pridat menu pre Kraj a Okres (tak ako to bolo v prvej verzii)

**Comment by kubocob** [comment]
Podla mna nema vyznam rolovat v celom zozname, Suggestions by mali prist az po napisani x znakov #43. Pripadne teda ako predvolene nachystat len zopar najvyznamnejsich miest.

**Comment by scholtz** [comment]
done
