### ISSUE TITLE
Scroll top pri navigacii

### ISSUE THREAD

**Issue by kubocob** [marsher/volby-zo-zahranicia#66]
Pouzivatel by mal vzdy vidiet zaciatok dalsieho kroku, pri posuvani sa dopredu v krokoch navigacie. 

Otazne je ci si ma pamatat poziciu ked ide naspat (ale to by bolo podla mna max nice to have, ak vobec)

**Comment by scholtz** [comment]
dik za tip. dik @s7anley za implementáciu
