### ISSUE TITLE
Nadhľady a zobrazenie pdf v novom okne nefunguje v IE a v niektorých ďalších prehliadačoch

### ISSUE THREAD

**Issue by Agoreddah** [marsher/volby-zo-zahranicia#67]
**Root cause**
Ide o chybu pdfmake.js knižnice a jej spôsobu generovania pdf objektov. Pdfko vygeneruje ako base64 encoded application/pdf objekt. V metóde createDocument sa tento objekt vkladá do iframe elementov. Internet explorer nepovoľuje použitie takéhoto objektu v navigácií alebo v iframoch. Inými slovami, nefunguje nadhľad, ani otvorenie pdfka v novom okne. Ďalším problémom sú staršie prehliadače ako safari, alebo firefox, ktoré s istými obmedzeniami nedokážu otvoriť taký pdf objekt, napr. ak base64 data url je príliš dlhé.

jeden z bugov - [pdfmake Bug#230](https://github.com/bpampuch/pdfmake/issues/230)

**Riešenie**
Internet explorer (týka sa to aj 11 a edge) a staršie prehliadače nebudú môcť zobraziť nadhľad, alebo otvoriť pdf v novom okne.
1. Treba vytvoriť varovnú hlášku pre všetkých používateľov internet explorera, aby použili iný prehliadač. Iframe skryť, alebo nahradiť ilustračným obrázkom.
2. Najnovší edge síce nevie otvoriť link na stiahnutie v novom okne, ale dokáže pdf objekt stiahnuť priamo. Do buttona Stiahnuť je možné zakomponovať metódu download(), pomocou ktorej sa automaticky stiahne pdfko. documentDefinition = {} musi byt globalny objekt a mal by sa rovnat premennej 'dd', ktorá vznikne v createDocument metóde. 

``` javascript
pdfMake.createPdf(documentDefinition).download();
```

**Comment by scholtz** [comment]
dik.. aj v ie 11 sa mi to podarilo stiahnut cez .download()

na hlavnu stranku som dal aj varovanie ak sa pouziva ie..
