### ISSUE TITLE
Vygenerovany e-mail - mala zmena

### ISSUE THREAD

**Issue by peterppp** [marsher/volby-zo-zahranicia#68]
Pacil sa mi ten napad mat v maile vygenerovany text.
mozno by sme tam mali pridat aj jednu vetu:

"Zaroven vas chcem poprosit o potvrdenie e-mailom ze žiadosť bola prijata a spracovaná"
Dakujem

**Comment by scholtz** [comment]
btw, hocikto si môže priamo na git stránke otvoriť npr súbor https://github.com/marsher/volby-zo-zahranicia/blob/master/js/site.js stlačiť editovať a navrhnúť zmeny.. :)

**Comment by scholtz** [comment]
done.. mozem to zavriet?

**Comment by peterppp** [comment]
super, dakujem
