### ISSUE TITLE
bug - PDF nie je generovane korektne (podpis sa objavi na druhej strane)

### ISSUE THREAD

**Issue by peterppp** [marsher/volby-zo-zahranicia#69]
po podpise PDF a stiahnuti do mobilu sa podpis objavi na druhej strane PDF (defakto neplatna ziadost)
Tiez podpis moze byt vacsi.
![img_2061](https://cloud.githubusercontent.com/assets/16066992/11747754/ea786cf0-a01c-11e5-844e-438eb9118c2d.PNG)

**Comment by scholtz** [comment]
dik za tip.. podpis bol posunuty trochu vyssie..
