### ISSUE TITLE
Podpora US formatu korespondencnej adresy

### ISSUE THREAD

**Issue by ghost** [marsher/volby-zo-zahranicia#71]
Meno Prievisko
1 Main Street, Unit 101 (cislo domu ako prve), alebo PO BOX 123 (bez cisla domu)
Anytown CA 12345
USA

**Comment by scholtz** [comment]
podpora formatovania adresy bola zavedena. Dakujeme za tip

**Comment by roman3x** [comment]
Toto si asi omylom zaviedol pre hlasovanie preukazom z domova a nie pre volby postou zo zahranicia.

**Comment by scholtz** [comment]
toto je uz opravene na teste
