### ISSUE TITLE
Detekcia browsera

### ISSUE THREAD

**Issue by rzelnik** [marsher/volby-zo-zahranicia#73]
Vo Firefoxe ver. 42.0 (v Ubuntu 15:10) sa mi na úvodnej stránke https://volby.digital/ zobrazuje nasledovná hláška:

POZOR! Používate prehliadač ktorý nepodporuje vytváranie náhľadov. Odporúčame Vám použiť chrome alebo firefox.

**Comment by scholtz** [comment]
mozem sa opytat co sa vam zobrazuje tu? https://volby.digital/useragent.php

**Comment by rzelnik** [comment]
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0

**Comment by scholtz** [comment]
je to teraz ok?

**Comment by rzelnik** [comment]
Áno. Ďakujem za rýchlu opravu.
