### ISSUE TITLE
Skrátenie výberu obce.

### ISSUE THREAD

**Issue by roman3x** [marsher/volby-zo-zahranicia#74]
Skratil by som vyber obce predvolenim Petrzalky, alebo Presova. A aj ostatné kraje(okresy) by mohli mať predvolené najpočetnejšie okresy(obce) a tým sa skráti počet klikov vyberu obce na 2/3-1/2.

Petržalka s 111000 obyvateľmi, alebo Prešov - najväčší kraj a zdroj východniarov najviac utekajúcich do zahraničia.

Bolo by to trosku viac JS kodu a o 1 prvok vacsi zoznam obci, kde bud bude pocet obyvatelov(a pri vybere sa najde najvacsie cislo, ktoremu sa da selected), alebo flag predvolenosti. 
Spravi to niekto, ci ten, co to vymyslel? :D

Na fb niekto radil, ze by sa mohlo zadavat PSC, ktore vyplni mesto atd... moze tam byt aj "Vyber svoje Mesto, alebo zadaj PSC". Avsak ked zada PSC a obecny urad bude amt specialne PSC, tak to nebude fungovat. Tak neviem.

**Comment by peterppp** [comment]
myslim ze tie tri stupne zoradene abecedne (kraj/Okres/Obec) su celkom dostatocne?

**Comment by scholtz** [comment]
ja stale rozmyslam nad tym ze by sme tam supli select2.. zo statistik vyplyva, ze navstevnost je teraz cca 70% desktop, 26% mobil, a 4% tablet.. Pre tych ludi na desktope by to ulahcilo vyber obce, a na mobil by to bolo otestovat ako sa to sprava..

**Comment by roman3x** [comment]
Neviem, co je select2, ale ak to bude na old mobile pomale, ako ten vypisovany a doplnany zo zoznamu 3k obci, hned na to pridem. Podla mna bude navstevnost mobilncyh zariadeni vonku vyssia.

**Comment by scholtz** [comment]
ok, skus to teraz otestovat..

**Comment by roman3x** [comment]
Rychlost je ok, ale ramcek je zbytocne velky. Horsie sa donho triafa aj myskou, aj prstom. Ak mozes easy zmenit, zvacsi pls vlastny prvok.

**Comment by scholtz** [comment]
ramcek sa mi zda byt rovkanky ako pri inych inputoch.. na to by sa mali skor pozret nejaki grafici :)

ja sa snazim nerobit grafiku..

**Comment by roman3x** [comment]
Zle som sa vyjadril - ramcek je rovnaky, ale plocha, kde musis kliknut/tuknut je mensia. Ale nie je to bug...

**Comment by roman3x** [comment]
Jeeej, aky pekny sen, ze si dorobil co som rozrobil predvolenie velkych miest. Ale mohol si dat tu Petrzalku prvu, alebo Presov. ;) 
Tak ak nikomu nevadi, ze je to v zozname na prvom mieste a nie podla abecedy tak je to super rychla implementacia a ten moj php kod ohladne toho "$topCities = get_top_cities();" a spol mozem vyhodit.

**Comment by scholtz** [comment]
Presovsky kraj je podla vsetkeho najludnatejsi..

**Comment by scholtz** [comment]
mozme tuto issue zatvorit?

**Comment by roman3x** [comment]
Tak tak, uz je to super! Konecne vychodniari dostali co im patri a ako najludnatejsi musia najmenej klikat. :+1:
