### ISSUE TITLE
Gramatické chyby

### ISSUE THREAD

**Issue by ziacik** [marsher/volby-zo-zahranicia#75]
Správne je "pre zložitý proces", nie "kvôli". A scanovať po slovensky je skenovať.

**Comment by peterppp** [comment]
Skontrolovat gramatiku potrebujeme. Prosim ohlasujte dalsie chyby ak najdete

**Comment by s7anley** [comment]
Túto issue by som zatvoril, ak sa niekto odhodlá na kompletnú opravu textu, tak by sa na to malo vytvoriť nové issue.

**Comment by scholtz** [comment]
dik za tip, a dik @s7anley za kód..
