### ISSUE TITLE
PSČ pole je ignorované

### ISSUE THREAD

**Issue by comp64** [marsher/volby-zo-zahranicia#76]
Voľba zo zahraničia, trvalý pobyt na Slovensku, PSČ trvalého pobytu: Predvyplnené nesprávne a aj keď si ho upravím, vo výslednom PDF ostáva stále nesprávne PSČ.
Pokiaľ sa mýlim, a má tam byť PSČ úradu, potom niet dôvodu vypĺňať ho.

**Comment by OndroNR** [comment]
V žiadosti o vydanie hlasovacieho preukazu je ten istý problém. Vo formulári sa mi predvyplní PSČ, opravím ho a v náhľade vidím to predvyplnené nesprávne PSČ.

**Comment by s7anley** [comment]
@comp64 môžeš uviesť presne údaje, ktoré si vyplnil nech si to môžem lokálne otestovať? Najlepšie aj screenshot.

**Comment by OndroNR** [comment]
Za mna som to vyplnil takto https://www.evernote.com/l/ADstBH2urkpHHJD8zfpA5WwwSJ9ScVTYrfY vygenerovana ziadost ma uz zle PSC, ked dam krok spat, je tam tiez zle PSC https://www.evernote.com/l/ADuE_neA6AZDK4bPfmZn_uHq2lw1CX8kEGo

**Comment by roman3x** [comment]
Je to sucasna vlastnost, ze vstupne pole PSC sa vypise podla mesta zo zoznamu https://github.com/marsher/volby-zo-zahranicia/blob/master/obce_08_12_2015.txt a dalej sa nevyuziva. Vyuziva sa iba to v zozname. Vacsie firmy a urady maju niekde pridelene samostatne PSC. Posta to doruci aj na to druhe PSC, lebo vedia kolka bije. Da sa povedat, ze to bude fungovat aj s tymto "zlym" PSC. 

Pre vyber dat obce zadanim IBA cislom PSC by sa patrilo sprevadzkovat citanie dat obce z formularoveho prvku a nie z premennej v skripte, ale to by bolo treba este vytvorit konverznu tabulku PSC vacsich miest, kde urad ma ine PSC, ako obyvatelia. Tipujem do 100 uradov ma ine PSC, ako ocakava volic. Viac aj v https://github.com/marsher/volby-zo-zahranicia/issues/35#issuecomment-163974870

**Comment by comp64** [comment]
@s7anley Relevantne polia:
Kraj: Bratislavsky kraj
Okres: Okres Bratislava 3
Mesto/Obec: Bratislava - Nove Mesto - Mestska cast
(Pred-vyplnene PSC): 832 91
(Mnou zadane) PSC: 831 01
Vo vygenerovanom PDF-ku sa objavi 832 91.

@roman3x Som trocha zmateny. Pokial sa pole nevyuziva, ako pises, preco je potom vo vygenerovanom PDF-ku to PSC uvedene?
Jeden zo stavov, ktory by som ocakaval:
- Bud nech je vo vygenerovanom PDF-ku take PSC, ake som si zadal,
- alebo nech tam nie je vobec,
- alebo pokial PSC nema byt pod kontrolou uzivatela, nech take pole nie je viditelne pri vyplnani formulara

**Comment by peterppp** [comment]
Myslim ze pole PSC by malo byt volne pre uzivatela.
Ta databaza PSC co mame obsahuje PSC na urady a nie na mesto.
Takze PSC pouzijeme z databazy na generovanie adresy uradu ALE nechame prazdne policko PSC pri sukromnej adrese aby si to mohol uzivatel vyplnit sam.

Tiez by som asi nechal prazdne policko pre OBEC na vyplnenie. Casto su to mensie obce co maju zlucene urady ale adresa obcana moze byt v inej obci. Napriklad ak byvate v obci Hurbanovce tak vas obecny urad je v obci Dedinka.

Dufam ze to dava zmysel. Toto je dolezite.

**Comment by ghost** [comment]
Ak ma byt PSC volne pre uzivatela - vyhladavat mesto podla PSC a zrusit kraj / okres / mesto pull downs? Databaza PSC by sa doplnila.

**Comment by peterppp** [comment]
to potrebujeme na najdenie spravnej adresy uradu obce

**Comment by peterppp** [comment]
myslim ze tie predvolby Kraj/Okres/Obec nechat tak.
Ale nechat uzivatela aby napisal PSC adresy sam + obec by mala byt editovatelna

**Comment by peterppp** [comment]
![note23](https://cloud.githubusercontent.com/assets/16066992/11764039/d0045990-a118-11e5-8408-cf38b3b5dd37.JPG)

priklad - ta adresa uradu je spravna
Ta adresa obcana je nespravna (Nitra ma 94901)

**Comment by scholtz** [comment]
issue je opravena. prosim skontrolujte, ci to takto moze byt..

**Comment by comp64** [comment]
Jo, kukol som aj kód. Ak to niekomu nefunguje, treba si vyčistit cache v prehliadači - klasický problém všetkých zmien v .js a .css.
Vďaka.

**Comment by OndroNR** [comment]
U mna to funguje, vdaka.

**Comment by roman3x** [comment]
Ako uzivatel som trosku zmeteny z toho, ze ked si editujem PSC v 3/7 a potom volim obec, PSC sa mi nezmeni.
