### ISSUE TITLE
Generator jazyk - PHP?

### ISSUE THREAD

**Issue by jmuransky** [marsher/volby-zo-zahranicia#77]
Rozmyslam trocha nad skulturnenim a stale mi vychadza, ze stranka by bola ovela citatelnejsia, keby bola trocha rozclenena a nebola cela v podstate len v index.html a site.js...
Na druhej strane bola dobra poznamka s tym, ze takto je to fakt jednoduchsie vo vysledku a pri nasadzovani...
Takze by som idealne chcel spojit a doplnit oba tieto svety - rozclenit jednotlive kroky navigacie a celkovo rozne kroky do roznych suborov a vo vysledku potom generovat jeden vystupny subor obsahujuci +- to co tam je teraz. 
No a ak sa do toho pustit, tak treba vediet co na to pouzit. Moznosti je viac. Diskutovalo sa tu nieco o PHP, takze to je jedna rozsirena volba. Dalsia je nodejs, ktory ma na taketo veci uz utilitky (grunt/gulp) + ostavame na javascripte. Este ina ocividna moznost je pribalit nejake shell skripty, len tam je nevyhoda pomerne silne viazanie na OS a pomerne obmedzene moznosti (concat je OK, ale include vramci layout sablony je viac problem)....

Vyhoda mimo lahsieho kolaborovania a oddelenia logiky by bol aj v tom, ze by sme mali realny building step a teda mozeme dorobit minifikaciu, merge atd...

**Comment by ujovlado** [comment]
@jmuransky na toto by bol idealny AngularJS. Jednotlive kroky by si mohol rozclenit do controllerov, HTMLko by sa rozbilo na viewy, bola by poriesena navigacia ... a cele by to bolo upratanejsie. Osobne by som to vsak v tejto verzii nerobil (bolo by s tym dost vela roboty). Skor by som pockal na nejaku verziu 2.0.

Hej, hodilo by sa mat Gulp + webserver, CSS pisat cez LESS, browsersync, minifikaciu a kopec dalsich :smile:.

**Comment by scholtz** [comment]
vselico by sa dalo pouzit.. 
proti php je npr to, ze teraz sa to da stiahnut ako zip priamo z gitu a pouzivat na lokalnom pocitaci.. ak by sme iba na krajsiu strukturovanos pouzivali phpcko, tak by to bolo asi menej efektivnejsie..

angular by siel, ale komplikovat taky jednoduchy projekt by bolo asi odveci..

mozno viacej komentarov do kodu by sa zislo, ale na to je uz ina issue..

ale dik za tip

**Comment by ujovlado** [comment]
@scholtz ano, kedze to ma cele bezat v browseri, PHPko je nanic.

> angular by siel, ale komplikovat taky jednoduchy projekt by bolo asi odveci..

Urcite to odveci nie je, dnes sa pouzivaju frameworky (kludne aj AngularJS) aj na mensie veci. Prave preto, aby si nic nemusel robit na kolene. :wink:.
