### ISSUE TITLE
UX - farby buttonov

### ISSUE THREAD

**Issue by mtruban** [marsher/volby-zo-zahranicia#8]
- podla mna nie je dobre, ked je jeden button modry a druhy cerveny. evokuje to rozdielne ulohy. resp. rozdielnu hierarchiu.

**Comment by musho** [comment]
- Rozmyslal som presne nad tymto
- Potom som to dal obidve sede, ale vyzerali obidve ako disabled
- Tak som to dal naspat, ale zacal som zase rozmyslat ze ci to aj neevokuje urcite politicke strany
- Dal som to teda zelene a oranzove, ale zistil som ze aj take strany su na SK
- Tak som to urobil cele cierno bielo, vyzeralo to ale ako keby si vyklikavas vlastne umrtne oznamenie
- Tak som to nehal tak a isiel spat

**Comment by mtruban** [comment]
lol. fetka. preco nemozu byt oboje modre?

**Comment by mtruban** [comment]
hento cervene s textom ODHLASENY fakt neni vramci UX dobre... ja sa bojim nato kliknut :)

**Comment by musho** [comment]
Lebo to vyzeralo ako SDKU generator ziadosti. 
Kludne to mozeme ale zmenit.

**Comment by mtruban** [comment]
lol. toto ma na tebe bavi.. sdku je uz KO. takze je to jedno :). dame to na modre.

**Comment by map4** [comment]
Vo Firefoxe stranka s tlacitkami zascrolluje dole a nie je vidno vetu - "Trvaly pobyt mam". Bez tej vety su tlacitka s textom "Registrovany na Slovensku" / "Odhlaseny" nie prilis zrozumitelne. 

Odporucam zmenit texty tlacitok "<b>Mám</b> trvalý na SR" / "<b>NEMÁM</b> trvalý pobyt na SR"

Technicka: umiestnenie kotvy # zahranicie je v podstate spravne, ale sucasny text prekryje stale viditelny pasik s logom volby.digital.

![trvpobyt-scroll](https://cloud.githubusercontent.com/assets/16252511/11739287/9b38466a-9fea-11e5-83e0-e946d0a1a59f.png)

**Comment by s7anley** [comment]
![snimka obrazovky 2015-12-13 o 0 05 48](https://cloud.githubusercontent.com/assets/640131/11764374/4b6cd0bc-a12d-11e5-8022-00ad6a717536.png)

?

**Comment by peterppp** [comment]
Ja by som to spravil obe modre. Ta bledomodra je pekna

**Comment by ujovlado** [comment]
@mtruban toto asi zavrite, @marsher to mergol v #101 :smile: . Ak vsak moze nastat nejaky krajny pripad, kedy to clovek nema ani na Slovensku ani v zahranici, nech na to spravia issue a moze sa tam dat napr. nejaky dovysvetlujuci text.

**Comment by kaqpa** [comment]
Na druhom tlačítku nechať "Odhlásený", takto sa tie tlačítka líšia len v 2 písmenkách, to sa strašne ľahko popletie

grammarnazi detail: buď v SR, alebo na Slovensku (na SK), nie na SR

**Comment by ujovlado** [comment]
@kaqpa pozri #101 resp. komentar dole https://github.com/marsher/volby-zo-zahranicia/pull/101#issuecomment-164301846
