### ISSUE TITLE
predvolene udaje pri volbe adresy (Kraj/Okres/Obec)

### ISSUE THREAD

**Issue by peterppp** [marsher/volby-zo-zahranicia#82]
Vo formulari pre volbu postou (s trvalym pobytom na SK) je v tych roletkach moznost zvolit "mimo uzemia SK" Tato moznost by tam nemala byt. Pretoze to vygeneruje nespravny formular.
Tiez je to logicky nespravne pretoze to je v sekcii "adresa trvaleho pobytu v SK"

![note22](https://cloud.githubusercontent.com/assets/16066992/11763774/1e90cc9c-a10f-11e5-9e4a-ed8595015610.JPG)

Volic s trvalym pobytom mimo SK musi pouzit druhy formular.

**Comment by scholtz** [comment]
done. prosim o kontrolu

**Comment by peterppp** [comment]
dakujem!
