### ISSUE TITLE
Prílohy ku e-mailu

### ISSUE THREAD

**Issue by comp64** [marsher/volby-zo-zahranicia#83]
Ak chcem žiadosť poslať e-mailom, a v poslednom kroku si kliknem na tlačítko, ktoré ma hodí priamo do e-mailového klienta cez 'mailto:' link, je prirodzené, že tam nemám priložené žiadne PDF (lebo to technicky nejde). Avšak aby na to ľudia nezabudli, navrhujem:

1) v pokynoch v poslednom kroku zdôrazniť (aspoň bold-om), aby odosielateľ nezabudol priložiť vygenerované PDF
2) a zároveň do vygenerovaného tela e-mailu zakomponovať kľúčové slovo "príloha" / "v prílohe", čím vo väčšine e-mail klientov podnietime upozornenie, že užívateľ zrejme chcel priložiť súbor.
Napr: V prílohe zasielam podpísanú žiadosť.

**Comment by scholtz** [comment]
dik za tip. moze to byt takto?

**Comment by roman3x** [comment]
V texte emailu by som text "V prílohe zasielam podpísanú žiadosť." dal na samostatny riadok(najradsej velkym :D), nech si to hlavne ja odosielatel vsimnem.

Do textu co sa zobrazi v kroku 7/7 vypisal na koniec aj tlf. cislo na urad. Mozno aj daky vCard format by mohol fungovat. Neviem. 

BTW, ked nevyplnim v 3/7 nic, tak mozem testovat dalej, ale v bode 7/7 mi nevypluje emailovu adresu uradu kam posielat.

**Comment by scholtz** [comment]
moze to byt takto?

to nevyplnenie 3/7 neviem replikovat.. mozes prosim uviest ako si sa tam dostal?

**Comment by roman3x** [comment]
Este by som tetusky na urade oslovil "Dobry den" a nesiel na nich priamo s §. :D
V cities.js mas tlf cislo na urad. Mozes ho pls za "Ak sa tak nestane, kontaktujte ich telefonicky." v 7/7 prilozit?

Chyba nevyplnenia je v Win 7, najnovsi FF. Ale tusim aj na androide. Aj po vymazani cache mozem odoslat dalej formular len s predvyplnenym PSC a ani len tie cervene hlasky nevidim, nie to, ze mam funkcne tlacitko dalej. Ked si to testujes, tak mas v prehliadaci uchovane polozky. tak treba si ich vymazat, co sposobi upozornenie, ale odoslat to uz ide. A po dlasom refreshi uz mozes aj bez cervenych warningov odosielat.

**Comment by filiplikavcan** [comment]
Ja by som do emailu nad text emailu pridal nieco taketo:

 == POZOR ===================================================
 PRED ODOSLANIM EMAILU PRILOZTE PRILOHY A ZMAZTE TOTO UPOZORNENIE
 ============================================================

**Comment by roman3x** [comment]
Som na 60% za. Cize ak ty na 90%, tak sa este 2 proti musia najst. :dancer:

**Comment by filiplikavcan** [comment]
Beriem spat. Skusal som to na mobile a kludne je mozne, ze pouzivatel tu hlasku ani neuvidi, tak ako ja, ked mu mailer hodi kurzor na koniec textu.

Sent from my phone

On Dec 13, 2015 8:33 PM, roman3x notifications@github.com wrote:

Som na 60% za. Cize ak ty na 90%, tak sa este 2 proti musia najst.

**Comment by peterppp** [comment]
Presne tak,
Pekne a slusne

**Comment by scholtz** [comment]
mozme toto uzavriet?

**Comment by roman3x** [comment]
Mne sa to paci. Uz je upozornenie pred mailom, po maili aj v texte mailu a kazde inym pismom, takze jedno z toho si hadam kazdy vsimne.
