### ISSUE TITLE
Pri nepouziteľnom zariadeni znemožniť zbytočné vypĺňovanie

### ISSUE THREAD

**Issue by roman3x** [marsher/volby-zo-zahranicia#85]
Pri vypnutom JS by mala byt namiesto tlacitka "Pripravit ziadost" HTML informacia o nutnosti zapnut JS a znovunacitat stranku. 
Pri mobilnej Opera 8 sa neda podpisat.
Opera a Chrome zatial nefunguje stiahnutie pdf. ( #20 ), co verim, ze pojde. 
Ale malo by sa mysliet dopredu na zariadenia, ktore nefunguju.

**Comment by scholtz** [comment]
pokracovanie v 
#108
