### ISSUE TITLE
Flow formularov

### ISSUE THREAD

**Issue by roman3x** [marsher/volby-zo-zahranicia#86]
V uvode neviem ci ludia potrebuju hned hore najvacsim pismom vidiet _"Až 98% ľudí zo zahraničia nevolilo v posledných parlamentných voľbách, pre zložitý proces a skoré termíny — my sme proces zjednodušili na 3 minúty, 20 slov a 8 klikov.
Pripravte si žiadosť cez telefón, bez tlačenia, skenovania či špeciálnej čítačky na občiansky preukaz. Stačí Vám na to adresa, rodné číslo a prípadne Váš pas."_
Pripomina mi to "Vitajte na nasej novej webovej stranke"
Zjednodusil by som to na "Zabezpecte si teraz moznost volit mimo volebnej miestnosti trvaleho bydliska. Potrva to iba 3 minúty - 20 slov a 8 klikov."

Krok 1 ("Trvalý pobyt mám") je super prehladny. Ale krok 2 ("V čase volieb budem mimo Slovenska") uz sa mi zda zlozitejsi, ako musi byt. Je tam toho vela a mohlo by byt iba:
VOLIT BUDEM
- "postou zo zahranicia" a pod tlacitkom vysvetlivky s datumom
- "z ktorejkolvek volebnej miestnosti na Slovensku" a pod tlacitkom vysvetlivky s datumom

3/7 
- Za RC a pred "Adresa trvalého pobytu v Slovenskej republike:" by mohlo byt vacsie odsadenie. 
- Rovnako aj medzi dvomi adresami, cize pred "Korešpondenčná adresa pre odoslanie hlasovacích lístkov alebo preukazu:". 
- "Vytvorit nahlad ziadosti" nebude lepsie iba "Vytvorit ziadost"?

4/7 Pod tlacitko "Stiahnut" by som dal text "Ak si chcem ziadost vytlacit poslat klasickou postou". Inak clovek nevie, na co tam je a ci ho ma stlacat. 

4/7 a 6/7 sa neda zmensit pdf prvok?

7/7 Nebude lepsie druhu cast cez klienta "alebo ak máte aktivovaného mailového klienta, vyskúšajte vytvoriť email automaticky:" dat na zaciatok a info o rucnom posielani za? Uz vidim opatrovatelky, ako lamentuju nad "nemoznostou" kopirovania textu do a zo schranky. :) Mozno aj vysvetlivky, alebo odkaz na externu stranku by sa sikol.

**Comment by roman3x** [comment]
Predpokladam, ze je mozne v bode 6/7 pred stiahnutim formulara znefunkcnit tlacitko a este viacej ho zasednut "Po ulozeni pokracujte tu". Pripadne ho ukazat az po ulozeni. Tiez by som zjednotil v oboch nazvy pre ulozenie/stiahnutie.

**Comment by roman3x** [comment]
Dik :+1: 
Snad text 3/7 "Ziadne udaje nie su odosielane cez internet" by mohol byt tentokrat mensi nech nestrasi-nezdrzuje. Len tusim ste to chceli zvyraznit...
Na konci by mohlo byt cislo este aj so Slovenskou predvolbou +421. Ked tam vidim druhe cislo, je moc nalepene na prvom. Ale to kaslat...
Na zaver by mohla byt pre muzske rodne cisla informacia, kolko to trvalo. :) A odkazy a vyzva na "spamovanie" kamosov cez twitter, fb, email. Hlavne tych zahranicnych. Priam sa to tam dole pyta ...nice to have

**Comment by peterppp** [comment]
dakujem za komentare. Suhlas, treba to skratit a ocesat. Myslim ze grafiku upravi Musho ked budu texty upravene a skontrolovane

Na tu prvu stranku som povodne chcel info nieco ako:

Priblizne 98% zo zahranicia nevolilo. Vacsina z nich sa nestihla vcas zaregistrovat. Nebudte medzi nimi.

alebo nieco v tom duchu... Vacsina ludi co pride na tento web je ta skupina co nevolila. Takze ich netreba stresovat hned na zaciatku. Skor nieco v tom zmysle - Vieme ze si nevolil - vacsina nevolila tiez. Fajn ze s tym chces nieco urobit, len to treba spravit cim skor - 50 dni pred volbami..
Ono ked som si robil prieskum medzi ludmi co ziju vonku tak vacsina to naozaj nesihla. Zacali si hladat info tak 2-3 tyzdne pred volbami co uz bolo zufalo po termine

Tie kliky a minuty a slova by som vypustil uplne.

**Comment by roman3x** [comment]
"Vieme ze si nevolil" :D - Vidíme ŤA!!! Ja mam rad statistiku, ale ci zrovna v tej situacii je ta statistika dolezita neviem. Mne sa tie kliky-minuty-slova pacia napriklad.

**Comment by peterppp** [comment]
mozno by sa hodilo odpocitavanie dni na prvej stranke kolko dni zostava do konca terminu na registraciu

**Comment by roman3x** [comment]
Fajn! :100: To je pre pouzivanie lepsie, ako statistika kolko ludi nevoli zo zahranicia.

**Comment by kaqpa** [comment]
"Predpokladam, ze je mozne v bode 6/7 pred stiahnutim formulara znefunkcnit tlacitko a este viacej ho zasednut "Po ulozeni pokracujte tu". Pripadne ho ukazat az po ulozeni. Tiez by som zjednotil v oboch nazvy pre ulozenie/stiahnutie."

pri mobilnych zariadeniach by to bolo kontraproduktivne - pdf sa stiahne automaticky uz pri nahlade

**Comment by roman3x** [comment]
Ak to nedame do JPG/GIF/PNG ( #100 ), tak to je pravda.

**Comment by roman3x** [comment]
Ked mi to stahuje nahlad dokumentu, mal by som tam oznamit, ze si to nema vsimat, ak ho nechce posielat postou.

**Comment by roman3x** [comment]
Tak isto neznaly potrebuje info, kde to ma hladat, ak to nebude jpg.

**Comment by eronisko** [comment]
Mozno trocha radikalny navrh, ale malo by zmysel zbavit sa aspon jedneho z tych nahladov?

V 4/7, ako pise @roman3x, moze byt to stiahnutie matuce pre noveho pouzivatela. Ak sa aj rozhodne si navrh stiahnut, flow tam skonci a uzivatel nedostane ziadne dalsie instrukcie, co je skoda.

Navrh:
- Pridat podpis k formularu a eliminovat podpisovu obrazovku. Tym padom mozeme zrusit aj nahlad ktory tam je predtym.
- Ak nepripojit podpis k formularu tak namiesto 'Stiahnut/Podpisat' by som tam dal 'Dokoncit/Podpisat' a ist na posledny screen, vid nasledujuci odstavec.

Co sa tyka 6/7 a 7/7, v 6/7 ako uzivatel vlastne nemam ziadnu volbu. Ten krok je zbytocny, lebo nema cenu ist na 7/7 bez stiahnutia PDFka. To znamena, ze pri 6/7 mozem akurat tak urobit chybu ak si ten subor nestiahnem.

Navrh:
- Ponuknut stiahnutie v 7/7 namiesto 6/7. Pripadne stiahnutie spustit automaticky.
- Zrusit 6/7. Nahlad by mohol byt v 7/7.

Ten flow od formularu by potom vyzeral takto:
4: Formular s podpisom
5: Stiahnutie s nahladom a instrukciami - koniec.

**Comment by roman3x** [comment]
Generovanie sa rozobera v #100. Teraz aj v #108 a aj niekde inde v starych issues pri hladani pdf najdes. S tym pdf pohli 2 bratia zmenou "vsetkeho", tak sa to nezmergovalo... Vyriesenie problemov s pdf by bol prechod na jpg, ktory tiez vela zmien vyzaduje... Ale zato ulahcuje zivot ludom. Na druhej strane teraz nebude velky problem, ze pobezi dobre iba PC verzia a teoreticky JPG verziu asi vhodnejsiu pre mobily a "ziadosti na poslednu chvilu" mozno niekto dorobi v priebehu nasledujucich dni.

**Comment by roman3x** [comment]
Co takto na poslednej obrazovke pred polsanim mailu odklik, alebo kratka info o kopirovani textu na androide a naslednom pastovani do emailu. Mam info, ze malo ludi ma nastaveneho emailoveho klienta.

**Comment by scholtz** [comment]
prave na androide by vsetci mali mat na vyber aplikacie bud gmail alebo nativny email.. myslim ze tam to hrozi najmenej.. skor ludia na pc s tym budu mat problem, a myslim ze je to dost jasne napisane ze si to mozu skopirovat z poslednej obrazovky.. ci nie?

**Comment by roman3x** [comment]
Maju tam na vyber, ale nastaveny ho nemaju... S kopirovanim textu maju useri probem, ale hlavne zeny VOBEC nevedia kopirovat. Nekopiruje sa lepsie, ked je to v inpute? Mozno ako kde...

**Comment by scholtz** [comment]
nemyslim ze sa oznacuje text lepsie v inpute alebo textarea ako vyber html.. na to je tam hlavne to tlacitko kopirovat nech to maju na jeden klik..

**Comment by roman3x** [comment]
Na PC v inpute, ked JS ho oznaci cely. Na mobile by to bolo asi kontrapprduktivne. Ale dobre ze pise so tom tlacitku, lebo ja som ho povazoval za daku debilinu. :D A isiel pohladom dalej. Pre takych ako ja treba dat vedla neho/nad/pod, proste smerom k prvemu **Šípku** s textom na co to sluzi. Ale aj tak. Zeny to nebudu vediet na mobile vlozit. Vacsina.

**Comment by roman3x** [comment]
Na stránke http://www.minv.sk/?nr16-posta2 som neasiel ziadne info o prilozeni pasu, alebo op. Je to iba pre odhlasenych z TP. http://www.minv.sk/?nr16-posta1 Ti tam maju aj cestne prehlasenie, tak to pridam do pdf. Dufam, ze to nemusi byt samostatny dokument. Ak nemate ine info.

**Comment by scholtz** [comment]
podla zakona to musi byt samostatny dokument.. som to dal naspet.. dik za implementaciu poste restante
