### ISSUE TITLE
zla e-mail adresa v ziadosti

### ISSUE THREAD

**Issue by peterppp** [marsher/volby-zo-zahranicia#90]
![note24](https://cloud.githubusercontent.com/assets/16066992/11766616/332f3660-a188-11e5-974b-0c0e6eb4decf.JPG)

V e-maile vytvorenom pre Ministerstvo vnutra je nespravny e-mail na prvu obec zo zoznamu obci. Spravna adresa ma byt :volby@minv.sk

V tejto ziadosti (Ziadost volbou bez trvaleho pobytu) moze byt adresa spravena napevno. Je tam len jedna jedina adresa (volby@minv.sk)

Tiez treba odstranit ten 'test res' z vygenerovanej spravy.

**Comment by scholtz** [comment]
email opraveny.. ten test res to je tvoje meno a priezvisko co si dal do ziadosti..

**Comment by peterppp** [comment]
Dajujem! to vygenerovane meno je super!! 
Dakujem.
