### ISSUE TITLE
udaje splnomocnenca

### ISSUE THREAD

**Issue by pavolgal** [marsher/volby-zo-zahranicia#91]
pre splnomocnenca je tam policko "Číslo občianskeho preukazu"
ale validacia hovori ze "Pre vytvorenie žiadosti je potrebné zadať rodné číslo splnomocnenca." (plus ja som k tomu v poslednom commite prihodil aj kontrolu formatu rodneho cisla)

ma to byt teda cislo obcianskeho alebo rodne cislo?
alebo tam maju byt obidve policka?

**Comment by peterppp** [comment]
podla Minv.sk tam ma byt cislo obcianskeho preukazu.

http://www.minv.sk/?nr16-preukaz
Pozri ziadost dole (vo worde)

**Comment by pavolgal** [comment]
dik, idem to fixnut
