### ISSUE TITLE
Jeden krok chyba v (zo zahranicia bez TP na SK)

### ISSUE THREAD

**Issue by peterppp** [marsher/volby-zo-zahranicia#92]
![image](https://cloud.githubusercontent.com/assets/16066992/11766690/d0d9211c-a18a-11e5-97ce-bf4ed3004079.png)

Chyba nam tam jeden krok - v ziadosti zo zahranicia (bez TP) treba prilozit aj fotku pasu.
V prvej verzii sa to pridavalo do PDF. To sme zrusili, kedze to mozno komplikovalo cele PDF.

Staci ked bude fotka pridana do e-mailu. Len to treba zdoraznit, pretoze momentalne to nie je jasne.
Tiez by bolo fajn ukazat priblizne co a ako treba odfotit :)

(Obrazok je stary nahlad na flow-chart co sme mali na zaciatku)

**Comment by scholtz** [comment]
a fungovalo to?

na to aby si nacital subor z disku tak vyplnenie suboru na odoslanie pokial viem tak nestaci..

to by bol pekny bezpecnostny bug keby sa dal nacitat cez js lubovolny subor z disku a potom ho spracovat..

**Comment by kaqpa** [comment]
To, pokial viem, nemalo fungovat, malo to v prvom rade pripomenut volicovi, ze ma pridat do mailu dalsiu prilohu (a ako ma vyzerat).

**Comment by scholtz** [comment]
Podla tohto by to teoreticky mohlo fungovat.. http://stackoverflow.com/questions/3582671/how-to-open-a-local-disk-file-with-javascript

Cast ludi tam vsak tvrdi ze to nejde, cast ze je to zablokovane v novych prehliadacoch a cast ze je to podporovane v html5.. Co som si urobil test, tak na windowsoch to funguje v kazdom novom prehliadaci, ale neviem ci by sme sa mali spoliehat ze to funguje prave u mna..

Tak co, dame foto pasu priamo do pdfka alebo ludom povieme aby ho nezabudli pripnut?

**Comment by ondrek** [comment]
Len dovysvetlenie —— javascript (resp HTML5 specka) dovoluju pristupovat k lokalnym suborom ALE uzivatel si ich musi sam zvolit v selecte/wizarde..  Z browsra (logicky) nemozes pristupovat k suborom na disku (to by kazda websajta vedela citat co mas na disku — a/k/a security problem).

Co sa tyka kompatibility (http://caniuse.com/#feat=fileapi), mne to funguje tiez vsade (osx) a ak sa bojime ze to nepojde, mozeme pohladat nejaky shim (https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-Browser-Polyfills#file-api).

**Comment by kaqpa** [comment]
Zatial im to urcite aspon pripomenme, IMHO komplikovat to den pred vydanim (pre chalanov ako aj pre uzivatelov) nie je dobry napad.

**Comment by scholtz** [comment]
som pridal zvyrazneny text aj na odoslanie pasu.. moze to byt takto? https://volby.digital/test/

**Comment by kaqpa** [comment]
V princípe áno, ale
-slovo "foto" v slovenčine ešte stále neexistuje, dajme tam fotografiu
-môže to byť aj scan (t.j. nezabudnite priložiť fotografiu alebo scan pasu)
-mala by tam byť ukážka, alebo spomenuté, že je to kvôli overeniu totožnosti. Nech to ľudí neprekvapí a  nenájde sa šikovník, čo im vrámci ochrany osobných údajov pošle toto:
![img_20151215_223926](https://cloud.githubusercontent.com/assets/8911929/11832377/38df6b9c-a37d-11e5-9d07-bf79e2423e15.jpg)

**Comment by scholtz** [comment]
@kaqpa ono ak by im poslali takuto ziadost tak podla zakona sa im skrati termin z 50 dni na 35 kde urad je povinny obcana vyzvat na doplnenie ziadosti (ak som to spravne pochopil)
