### ISSUE TITLE
scroll menu iOS

### ISSUE THREAD

**Issue by peterppp** [marsher/volby-zo-zahranicia#95]
pred par dnami mi iPhone umoznil volit mesto Kraj/Okres/Obec cez taketo menu:
![image](https://cloud.githubusercontent.com/assets/16066992/11766762/5ee53156-a18d-11e5-9417-e720cea91d15.png)

teraz je to nazad ku klasikym roletkam.
Neviem ci je to zlozite spravit.

**Comment by peterppp** [comment]
presiel som si moznosti tychto formularov. Korektne to funguje pri volbe formatu adresy (SK/US) takze by to mohlo fungovat aj pri obciach. Mozno tam bolo len nieco zmenene/

**Comment by peterppp** [comment]
![image](https://cloud.githubusercontent.com/assets/16066992/11769471/01d5d1c0-a1e0-11e5-8625-d2897ba754d5.png)

Myslim toto. Na jednom menu to ide tak snad to pojde aj na druhom?

**Comment by scholtz** [comment]
takze ak sme na macu tak nepouzivat select2

mne sa na androide viac paci to na pravo, lebo ked sa pise na klavesnici tak sa da rychlejsie najst npr rimavska sobota..

**Comment by jmichalco** [comment]
co sa tyka dropdownov - jednoznacne som za tu moznost nalavo, ta napravo (co je na stranke teraz) sa blbo klika, najma na mobile ak ma clovek velke prsty ako ja. Vedeli by ste to zmenit?

**Comment by scholtz** [comment]
ok, na ios je to vypnute..
