### ISSUE TITLE
Obec moze mat viac PSC

### ISSUE THREAD

**Issue by filiplikavcan** [marsher/volby-zo-zahranicia#99]
Napr. pri ulica Krajna v Ruzinove ma PSC 821 04 a nie 827 05. Je mozne ziskat databazu, kde by boli mapovane ulice na PSC?

**Comment by roman3x** [comment]
Problem je, ze niektore urady vo vacsich mestach maju samostatne PSC. Rozoberalo sa to https://github.com/marsher/volby-zo-zahranicia/issues/35#issuecomment-163974870 Jedna budova, dva urady, 2 PSC. Ale podstatne je vediet, ze posta to doruci aj na PSC obce a zvlastne PSC je v podstate dobre iba na automatizovane strojne triedenie. 
A funkcnost sa rozobera v #76

**Comment by scholtz** [comment]
PSČ je editovateľné .. PSČ úradu sa bere z databázi obcí..
